# Generated by Django 5.2.14 on 2026-05-11 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Namespaced event identifier (e.g. ingress.webhook_received).",
                        max_length=120,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured event data. Never raw PII — IDs and hashes only.",
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Correlates events across a single pipeline turn. Set by ingress at request entry; propagated via ContextVar.",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant in scope at emission. Null for system-level events.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="events_even_tenant__950ad9_idx"
                    ),
                    models.Index(fields=["trace_id"], name="events_even_trace_i_f9d603_idx"),
                    models.Index(
                        fields=["event_type", "-created_at"], name="events_even_event_t_d1f8db_idx"
                    ),
                ],
            },
        ),
    ]
