# Generated by Django 5.2.14 on 2026-05-17 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0002_clientprofile"),
        ("tenancy", "0005_tenant_manager_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("certificate", "Gift certificate")],
                        default="certificate",
                        help_text="What the order is for. Only 'certificate' in Phase 1.",
                        max_length=24,
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order amount in roubles. Clamped to [500, 100000] at the tool layer — the database column doesn't enforce the range (admin-side creation must remain unconstrained for edge-case fixups).",
                        max_digits=10,
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name printed on the certificate. Empty when the client buys for themselves.",
                        max_length=150,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Where to email the certificate link. Empty when the client wants the link delivered in-bot only.",
                        max_length=254,
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Buyer's email — used by YooKassa for the 54-FZ receipt (FT-13 plumbing lands in a follow-up).",
                        max_length=254,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short Russian description shown to the buyer on the YooKassa checkout page.",
                        max_length=255,
                    ),
                ),
                (
                    "external_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="YooKassa payment.id (UUID). Indexed because the webhook handler looks orders up by this column.",
                        max_length=64,
                    ),
                ),
                (
                    "checkout_url",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="YooKassa-hosted checkout URL. The bot sends the user here via an inline 'Оплатить' button.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("awaiting_payment", "Awaiting payment"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by the fulfilment task on the ``payment.succeeded`` webhook.",
                        null=True,
                    ),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked channel identity. SET_NULL — orders persist as a receipt even after a GDPR-erasure of the BotUser.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — orders are a billing / forensic artefact and must outlive a tenant-delete request (audit retention requirement). Tenant deletion requires an explicit data-purge first.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(
                        help_text="YooKassa event UUID. UNIQUE — re-delivery hits this constraint and the handler short-circuits.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="YooKassa event slug — e.g. ``payment.succeeded``, ``payment.canceled``, ``refund.succeeded``.",
                        max_length=64,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Full upstream payload. Used for replay / debug. MUST NOT contain the YooKassa secret key (the webhook body doesn't include credentials, but a defence-in-depth scrub at write time is the handler's responsibility).",
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="True once the handler ran the side effect (status flip + fulfilment enqueue) for this event.",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked order. SET_NULL because a webhook for an unknown order id is still forensic evidence of upstream behaviour and must persist.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment event",
                "verbose_name_plural": "Payment events",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "-created_at"], name="orders_orde_tenant__b7367d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["tenant", "status"], name="orders_orde_tenant__291115_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["-received_at"], name="orders_paym_receive_a9f37a_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(fields=["event_type"], name="orders_paym_event_t_7bd5d0_idx"),
        ),
    ]
