# Generated by Django 5.2.14 on 2026-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-tenant feature flags JSON. Sprint 4+ consumers read entries like {'voice_input': true}; missing keys default to False at the call site.",
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="locale",
            field=models.CharField(
                default="ru-RU",
                help_text="BCP-47 locale tag for tenant-default language. Per-BotUser overrides land alongside personalisation work.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                default="free",
                help_text="Billing plan tier. Free during Phase 0; Sprint 9+ billing module will gate features by this value.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                help_text="IANA timezone for tenant-local rendering of times in messages (e.g. 'завтра в 10:00'). Falls back to UTC if invalid.",
                max_length=64,
            ),
        ),
    ]
