# Generated by Django 5.2.14 on 2026-05-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="last_catalog_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Cursor — `?since=` filter for the next catalog sync run. NULL → full resync. Written by apps.catalog.services.sync after a successful pull-upsert cycle.",
                null=True,
            ),
        ),
    ]
