# Generated by Django 5.2.14 on 2026-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0003_tenant_last_catalog_sync_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="shadow_mode",
            field=models.BooleanField(
                default=False,
                help_text="When True the orchestrator writes shadow rows but does NOT send outbound messages to the user. Used during shadow-mode soak before canary cutover. See docs/runbooks/shadow-mode-launch.md.",
            ),
        ),
    ]
