# Generated by Django 5.2.14 on 2026-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0004_tenant_shadow_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="manager_chat_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MAX chat_id of the salon manager who receives escalation alerts for T-24h reminders the client never replied to. Empty disables escalation for the tenant; status still flips to ESCALATED but no outbound message is dispatched.",
                max_length=128,
            ),
        ),
    ]
