# Generated by Django 5.2.14 on 2026-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0005_tenant_manager_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Service tenant — not a real salon. Holds shared infrastructure data (e.g. cross-salon KB corpus). Cannot be deleted from admin.",
            ),
        ),
    ]
