# Generated by Django 5.2.14 on 2026-06-05 09:29

from django.db import migrations, models

# Minimal Penza-pilot backfill (#1018): the pilot salons are all in Penza,
# so seed existing tenants' city. Idempotent + reversible (reverse clears
# only what this set — leaves operator edits alone is out of scope, reverse
# is a no-op restore to blank).
_PILOT_CITY = "Пенза"


def _backfill_pilot_city(apps, schema_editor):
    Tenant = apps.get_model("tenancy", "Tenant")
    # Only rows still blank — never clobber a city an operator already set.
    Tenant.objects.filter(city="").update(city=_PILOT_CITY)


def _noop_reverse(apps, schema_editor):
    # Reverse leaves data as-is: dropping the column (the AddField reverse)
    # removes the values anyway, so a data-reverse here would be redundant.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Salon city for marketplace discovery (e.g. «Пенза»). Blank = not yet set; minimal geo for the pilot (no lat/lng).",
                max_length=120,
            ),
        ),
        migrations.RunPython(_backfill_pilot_city, _noop_reverse),
    ]
