# Generated by Django 5.2.14 on 2026-08-16 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_masterservice_ayla_edge_provenance"),
        ("identity", "0014_seed_global_bot_tenant"),
        ("tenancy", "0010_tenant_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("receptionist", "Receptionist"),
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                            ("master", "Master"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of the normalized code. The code itself is shown once at issue time and never stored.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-form label for the issuer: who this code was meant for. Not shown to the recipient.",
                        max_length=200,
                    ),
                ),
                (
                    "catalog_master",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for role=master: the EXISTING catalog row this invite links a person to. Never used to create a master.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_invites",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who issued it. NULL for invites issued by a management command — the pilot's first owner has no one to be invited by.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_invites",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_staff_invites",
                        to="identity.botuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff invite",
                "verbose_name_plural": "Staff invites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "used_at", "expires_at"],
                        name="tenancy_sta_tenant__1632e7_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("catalog_master__isnull", False), ("role", "master")),
                            models.Q(
                                models.Q(("role", "master"), _negated=True),
                                ("catalog_master__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="staff_invite_master_requires_catalog_master",
                    )
                ],
            },
        ),
    ]
