# Generated by Django 5.2.14 on 2026-08-21 09:51
"""DRF-1227 — one ACTIVE staff row per (tenant, person, role).

The plain ``unique_together`` this replaces contradicted the field next to
it: ``deactivated_at`` exists so a revoked assignment survives for audit,
but a total unique index meant that history could hold exactly one entry
per role. Re-hiring somebody whose access had been revoked raised
IntegrityError instead of granting the role back.

Safe in both directions on live data: dropping a unique index never
conflicts, and the partial index cannot conflict either — two active rows
with the same (tenant, bot_user, role) were impossible under the index
being dropped.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0014_seed_global_bot_tenant"),
        ("tenancy", "0011_staffinvite"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantstaff",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tenantstaff",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deactivated_at__isnull", True)),
                fields=("tenant", "bot_user", "role"),
                name="unique_active_staff_role",
            ),
        ),
    ]
