# Generated by Django 5.2.14 on 2026-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0013_tenant_last_catalog_sync_ok_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="manager_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MAX user_id менеджера салона — идентификатор ЧЕЛОВЕКА, а не диалога, и потому верный для любого нашего бота (DRF-1559). Заполнен — адресуемся по нему; пуст — откатываемся на manager_chat_id, который работает только для бота, из чьего диалога он взят.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="manager_chat_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="УСТАРЕВШЕЕ (DRF-1559): MAX chat_id менеджера. chat_id — это идентификатор ДИАЛОГА, он верен только для того бота, из переписки с которым его скопировали; салонный бот, отправляя туда, получает 404 dialog.not.found. Читается, пока manager_user_id пуст, — чтобы уже настроенные салоны не замолчали в день выкладки. Заполните manager_user_id и очистите это поле.",
                max_length=128,
            ),
        ),
    ]
