# Generated by Django 5.2.14 on 2026-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0014_tenant_manager_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Почтовый адрес салона. NULL — источник об адресе не сказал ничего (не «пустой адрес»); "" — источник сказал, что адреса нет. Пишется синхронизацией каталога из ключа ``tenant_address`` фида специалистов, когда тот появится (DRF-1587); до тех пор заполняется вручную. Не выводится из адресов мастеров — это была бы лотерея (OPEN_DECISIONS §45).',
                max_length=500,
                null=True,
            ),
        ),
    ]
