# Generated by Django 5.2.14 on 2026-09-08 13:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_catalogfaq_options_and_more"),
        ("identity", "0022_botuser_blocked_at_botuser_blocked_by_username_and_more"),
        ("tenancy", "0015_tenant_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffinvite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Приглашение сотрудника",
                "verbose_name_plural": "Приглашения сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "Салон",
                "verbose_name_plural": "Салоны",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantstaff",
            options={
                "verbose_name": "Доступ сотрудника",
                "verbose_name_plural": "Доступы сотрудников",
            },
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="catalog_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for role=master: the EXISTING catalog row this invite links a person to. Never used to create a master.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_invites",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="code_hash",
            field=models.CharField(
                db_index=True,
                help_text="SHA-256 of the normalized code. The code itself is shown once at issue time and never stored.",
                max_length=64,
                unique=True,
                verbose_name="Хеш кода приглашения",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who issued it. NULL for invites issued by a management command — the pilot's first owner has no one to be invited by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.botuser",
                verbose_name="Кто пригласил",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="expires_at",
            field=models.DateTimeField(db_index=True, verbose_name="Действует до"),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Free-form label for the issuer: who this code was meant for. Not shown to the recipient.",
                max_length=200,
                verbose_name="Заметка",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("master", "Master"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_invites",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Использовано"
            ),
        ),
        migrations.AlterField(
            model_name="staffinvite",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_staff_invites",
                to="identity.botuser",
                verbose_name="Кто воспользовался",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Почтовый адрес салона. NULL — источник об адресе не сказал ничего (не «пустой адрес»); "" — источник сказал, что адреса нет. Пишется синхронизацией каталога из ключа ``tenant_address`` фида специалистов, когда тот появится (DRF-1587); до тех пор заполняется вручную. Не выводится из адресов мастеров — это была бы лотерея (OPEN_DECISIONS §45).',
                max_length=500,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Salon city for marketplace discovery (e.g. «Пенза»). Blank = not yet set; minimal geo for the pilot (no lat/lng).",
                max_length=120,
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Заведён"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="daily_cost_cap_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Daily USD spend budget. Cost per call is computed from apps.llm.pricing.compute_cost; once the day's accumulator crosses this value the cost-tracker rejects further LLM calls via TenantQuotaExceeded. Reset at 00:00 UTC.",
                max_digits=8,
                verbose_name="Дневной лимит расходов, $",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="daily_token_cap",
            field=models.BigIntegerField(
                default=1000000,
                help_text="Daily LLM token budget (input + output, completion + embedding). Reset at 00:00 UTC. The pre-call gate in apps.llm.cost_tracker rejects with TenantQuotaExceeded once the counter reaches this value.",
                verbose_name="Дневной лимит токенов",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-tenant feature flags JSON. Sprint 4+ consumers read entries like {'voice_input': true}; missing keys default to False at the call site.",
                verbose_name="Включённые возможности",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор салона",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="False hides the tenant from default queries. Soft-disable a tenant without dropping data — billing freezes, scoping middleware returns 403 (strict mode) or routes to None (audit mode).",
                verbose_name="Салон подключён",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Service tenant — not a real salon. Holds shared infrastructure data (e.g. cross-salon KB corpus). Cannot be deleted from admin.",
                verbose_name="Системный салон",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_catalog_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Upstream content watermark — max(updated_at) over the rows the last successful pull returned. NOT a run timestamp: a static catalog freezes this value on a healthy contour. Use last_catalog_sync_ok_at to judge freshness of the SYNC.",
                null=True,
                verbose_name="Последняя попытка синхронизации",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_catalog_sync_ok_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Wall-clock of the last SUCCESSFUL catalog sync run for this tenant. NULL → never synced. Age above CATALOG_SYNC_STALE_AFTER_SECONDS pages the on-call channel (apps.catalog.tasks.alert_stale_catalog_sync).",
                null=True,
                verbose_name="Последняя успешная синхронизация",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="locale",
            field=models.CharField(
                default="ru-RU",
                help_text="BCP-47 locale tag for tenant-default language. Per-BotUser overrides land alongside personalisation work.",
                max_length=16,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="manager_chat_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="УСТАРЕВШЕЕ (DRF-1559): MAX chat_id менеджера. chat_id — это идентификатор ДИАЛОГА, он верен только для того бота, из переписки с которым его скопировали; салонный бот, отправляя туда, получает 404 dialog.not.found. Читается, пока manager_user_id пуст, — чтобы уже настроенные салоны не замолчали в день выкладки. Заполните manager_user_id и очистите это поле.",
                max_length=128,
                verbose_name="Идентификатор диалога менеджера в MAX",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="manager_user_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MAX user_id менеджера салона — идентификатор ЧЕЛОВЕКА, а не диалога, и потому верный для любого нашего бота (DRF-1559). Заполнен — адресуемся по нему; пуст — откатываемся на manager_chat_id, который работает только для бота, из чьего диалога он взят.",
                max_length=128,
                verbose_name="Идентификатор менеджера в MAX",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                help_text="Human-readable name shown in admin and billing.",
                max_length=200,
                verbose_name="Название салона",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                default="free",
                help_text="Billing plan tier. Free during Phase 0; Sprint 9+ billing module will gate features by this value.",
                max_length=32,
                verbose_name="Тариф",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="shadow_mode",
            field=models.BooleanField(
                default=False,
                help_text="When True the orchestrator writes shadow rows but does NOT send outbound messages to the user. Used during shadow-mode soak before canary cutover. See docs/runbooks/shadow-mode-launch.md.",
                verbose_name="Теневой режим: бот не пишет клиенту",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                help_text="Lowercase identifier used in URLs and the X-Tenant header. Letters, digits, hyphen, underscore. Must start with a letter or digit. Cannot be changed after creation.",
                unique=True,
                verbose_name="Код салона",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="BotFather access token for this tenant's Telegram bot. NEVER log this value — masked in __repr__ and admin list views. See docs/runbooks/telegram-bot-onboarding.md.",
                max_length=128,
                verbose_name="Токен бота Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="telegram_webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Per-tenant secret the operator generates (e.g. secrets.token_urlsafe(32)) and registers with Telegram's setWebhook ?secret_token=…. Telegram sends it back in X-Telegram-Bot-Api-Secret-Token on every webhook POST; the webhook view verifies with hmac.compare_digest.",
                max_length=64,
                verbose_name="Секрет вебхука Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                help_text="IANA timezone for tenant-local rendering of times in messages (e.g. 'завтра в 10:00'). Falls back to UTC if invalid.",
                max_length=64,
                verbose_name="Часовой пояс",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="bot_user",
            field=models.ForeignKey(
                help_text="The person holding this role, identified by their channel-scoped BotUser. PROTECT mirrors the tenant FK — a delete must not silently drop role history.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_assignments",
                to="identity.botuser",
                verbose_name="Аккаунт в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the staff row was created.",
                verbose_name="Доступ выдан",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="BotUser who created this assignment — audit trail for operator-led promotions. NULL allowed for system-created rows (seed data, management commands, migrations).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.botuser",
                verbose_name="Кем выдан доступ",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the role was revoked. NULL = active. Soft deactivation preserves the historical assignment for audit; the role resolver ignores rows with this set, and the partial unique-Owner constraint only counts active rows so an Owner handover can deactivate the old row then create the new one.",
                null=True,
                verbose_name="Доступ снят",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                ],
                db_index=True,
                help_text="One of owner / admin / receptionist (ADR-0008). Owner uniqueness is enforced per-tenant via partial unique constraint below.",
                max_length=16,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="tenantstaff",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. PROTECT — dropping a tenant must not silently nuke the audit trail of who held what role.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
    ]
