# Generated by Django 5.2.17 on 2026-09-16 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0016_alter_staffinvite_options_alter_tenant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "platform_operations",
                        "Операции платформы: действия поперёк салонов",
                    )
                ],
                "verbose_name": "Салон",
                "verbose_name_plural": "Салоны",
            },
        ),
    ]
