# Generated by Django 5.2.14 on 2026-09-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0018_ayla_operations_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinvite",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Отозвано"),
        ),
    ]
