# Generated by Django 5.2.14 on 2026-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0020_drf2595_timezone_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="Europe/Moscow",
                help_text="IANA timezone of the salon: its day, its hours in messages (e.g. 'завтра в 10:00'). Read ONLY via apps.tenancy.timezones.salon_zone (DRF-2595): empty → Europe/Moscow, an unknown name → Europe/Moscow plus a tenancy.bad_tenant_tz log line; on strict paths (booking create, slots) both refuse, logged as tenancy.empty_tenant_tz / tenancy.bad_tenant_tz. Never UTC.",
                max_length=64,
                verbose_name="Часовой пояс",
            ),
        ),
    ]
