# Generated by Django 5.2.17 on 2026-09-20 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0031_drf2133_data_subject_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goal_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("direction", "Направление (C04.1)"),
                            ("absence", "Нет рекомендации (C04.4)"),
                        ],
                        default="direction",
                        max_length=16,
                    ),
                ),
                ("what", models.CharField(blank=True, default="", max_length=200)),
                ("subline", models.CharField(blank=True, default="", max_length=300)),
                ("why", models.JSONField(blank=True, default=list)),
                ("facts", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "reaction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("why_requested", "Почему"),
                            ("alternative_requested", "Другой вариант"),
                            ("rejected", "Не сейчас"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("reacted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="identity.botuser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["bot_user", "created_at"], name="reco_user_created_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bot_user", "fingerprint"),
                        name="recommendation_user_fingerprint_uniq",
                    )
                ],
            },
        ),
    ]
