# Generated by Django 5.2.14 on 2026-05-13 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KbDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("service", "Service description"),
                            ("master", "Master bio / specialisation"),
                            ("contraindication", "Health screening contraindication"),
                            ("faq", "Frequently-asked-question entry"),
                            ("help_article", "Help-article long-form"),
                            ("legal", "Legal / policy text"),
                        ],
                        help_text="Locked six-value taxonomy. Drives chunking strategy (K3) and ChromaDB metadata payload (K4).",
                        max_length=32,
                    ),
                ),
                (
                    "source_uri",
                    models.CharField(
                        help_text="Stable provenance key. Catalog-mirrored: `mysite://services/<external_id>`. Manual: free-form slug.",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonic per source_uri. Bumped when upstream content changes; old versions stay queryable for forensics.",
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="ru-RU",
                        help_text="IETF locale tag. Sprint 7 ships ru-RU only; field reserved so Phase 1 can add en-US without migration.",
                        max_length=16,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form per-doc context — referenced master IDs, parent service slug, etc. Surfaces in ChromaDB metadata.",
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of `content` (hex). K4 ingester compares to skip embedding unchanged content. Auto-computed on save via :meth:`compute_checksum`.",
                        max_length=64,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full source text. Chunks (K3) rebuilt from this on every ingest run."
                    ),
                ),
                (
                    "embedded_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="NULL = needs embedding. K4 ingester selects `embedded_at IS NULL OR embedded_at < updated_at`.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — KB content is cheap to re-ingest from the catalog mirror; tenant delete also wipes the ChromaDB collection (K11 signal).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_documents",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB document",
                "verbose_name_plural": "KB documents",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "doc_type", "-updated_at"],
                        name="kb_kbdocume_tenant__a9e72c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "source_uri"], name="kb_kbdocume_tenant__06eb31_idx"
                    ),
                ],
                "unique_together": {("tenant", "source_uri", "version")},
            },
        ),
    ]
