# Generated by Django 5.2.5 on 2026-05-19 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0004_backfill_attribution"),
        ("identity", "0002_clientprofile"),
        ("tenancy", "0008_tenant_cost_caps"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        help_text="Current redeemable points. Always derivable from LoyaltyEvent sum; cached here for O(1) reads at every booking checkout. Reconciliation cron (future) verifies the cache.",
                    ),
                ),
                (
                    "enrolled",
                    models.BooleanField(
                        default=True,
                        help_text="Per Q-L5 — automatic enrollment on first earning event. Customer can opt out via profile preferences (Q-L12); set False + stamp opted_out_at. Existing balance retained but no new earnings.",
                    ),
                ),
                (
                    "opted_out_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when customer disables loyalty in profile preferences. Subscriber checks this before crediting (Q-L12 — retain balance, stop accrual, allow redemption).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="The customer this account belongs to. CASCADE because loyalty data follows the customer's lifecycle (OP6 erasure deletes the BotUser → account goes with it; AuditLog keeps the trail).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_account",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — loyalty rows are billing-adjacent forensic artifacts; explicit purge before tenant deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_accounts",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty account",
                "verbose_name_plural": "Loyalty accounts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("earn_visit", "Earn — visit completed"),
                            ("earn_referral", "Earn — referral converted"),
                            ("earn_birthday", "Earn — birthday bonus"),
                            ("earn_review", "Earn — review left"),
                            ("earn_return", "Earn — long-gap return"),
                            ("redeem", "Redeem — discount applied"),
                            ("manual_adjust", "Manual — admin adjustment"),
                            ("refund_revoke", "Revoke — booking refunded/cancelled"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "points_delta",
                    models.IntegerField(
                        help_text="Signed delta applied to balance. Positive for earn, negative for redeem/revoke/manual_adjust(down)."
                    ),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="Balance after this event applied. Stored (not computed) so dispute drilling doesn't have to replay the whole history."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Human-readable reason. Free-form but conventional: "visit completed (booking <uuid>)", "manual: customer goodwill", "booking.cancelled cascade".',
                        max_length=200,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Implementation tags (correlation_id from envelope, service price snapshot, calc breakdown). PII-free.",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The account this event mutates. CASCADE follows account lifecycle (which itself cascades from BotUser per OP6 erasure).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="loyalty.loyaltyaccount",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source booking for visit-bound events. SET_NULL — the event row outlives the booking row when booking is purged (analytics preserves the earning fact without the underlying booking).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_events",
                        to="booking.bookingrequest",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_events",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty event",
                "verbose_name_plural": "Loyalty events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loyaltyaccount",
            index=models.Index(
                fields=["tenant", "-balance"], name="loyalty_loy_tenant__a650fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyevent",
            index=models.Index(
                fields=["account", "-occurred_at"], name="loyalty_loy_account_ce50d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loyaltyevent",
            index=models.Index(
                fields=["tenant", "event_type", "-occurred_at"],
                name="loyalty_loy_tenant__d5dc22_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltyevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False), ("event_type", "earn_visit")),
                fields=("account", "event_type", "booking"),
                name="loyalty_earn_visit_unique_per_booking",
            ),
        ),
    ]
