# Generated by Django 5.2.5 on 2026-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_bookingrequest_completed_at"),
        ("loyalty", "0001_initial"),
        ("tenancy", "0008_tenant_cost_caps"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="loyaltyevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False), ("event_type", "refund_revoke")),
                fields=("account", "event_type", "booking"),
                name="loyalty_refund_revoke_unique_per_booking",
            ),
        ),
    ]
