# Generated by Django 5.2.5 on 2026-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0002_loyaltyevent_loyalty_refund_revoke_unique_per_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyaccount",
            name="tier",
            field=models.CharField(
                choices=[
                    ("starter", "Стартовый"),
                    ("regular", "Постоянный"),
                    ("favorite", "Любимый"),
                ],
                db_index=True,
                default="starter",
                help_text="Current loyalty tier per handoff §3. Recomputed after every EARN_VISIT and REFUND_REVOKE via apps.loyalty.services.recompute_tier. Stamps tier_changed_at and writes a TIER_CHANGED LoyaltyEvent + emits customer.tier.changed envelope only when the value differs.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="tier_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the account last transitioned tier. NULL on accounts that have always been Стартовый.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loyaltyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("earn_visit", "Earn — visit completed"),
                    ("earn_referral", "Earn — referral converted"),
                    ("earn_birthday", "Earn — birthday bonus"),
                    ("earn_review", "Earn — review left"),
                    ("earn_return", "Earn — long-gap return"),
                    ("redeem", "Redeem — discount applied"),
                    ("manual_adjust", "Manual — admin adjustment"),
                    ("refund_revoke", "Revoke — booking refunded/cancelled"),
                    ("tier_changed", "Tier — threshold crossed"),
                ],
                max_length=24,
            ),
        ),
    ]
