# Generated by Django 5.2.5 on 2026-05-19 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_bookingrequest_completed_at"),
        ("identity", "0002_clientprofile"),
        ("loyalty", "0003_loyaltyaccount_tier_loyaltyaccount_tier_changed_at_and_more"),
        ("tenancy", "0008_tenant_cost_caps"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending — awaiting referee's first visit"),
                            ("completed", "Completed — referrer credited"),
                            ("expired", "Expired (forward-compat)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="The booking whose completion triggered the credit. SET_NULL — the referral fact outlives the booking row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_completions",
                        to="booking.bookingrequest",
                    ),
                ),
                (
                    "referee_customer",
                    models.ForeignKey(
                        help_text="The new customer being invited (referrer earns when this user's first visit completes). UNIQUE per tenant — see constraint.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_as_referee",
                        to="identity.botuser",
                    ),
                ),
                (
                    "referrer_customer",
                    models.ForeignKey(
                        help_text="The customer who invited (will be credited). CASCADE: if the referrer is GDPR-purged, their referral rows go with them; audit log retains the credit fact.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_referrals",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyalty referral",
                "verbose_name_plural": "Loyalty referrals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "referrer_customer", "-created_at"],
                        name="loyalty_loy_tenant__f56c31_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"], name="loyalty_loy_tenant__37796e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "referee_customer"),
                        name="loyalty_referral_unique_referee_per_tenant",
                    )
                ],
            },
        ),
    ]
