# Generated by Django 5.2.5 on 2026-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0004_loyaltyreferral"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyaccount",
            name="tier_reset_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Phase 2.c — floor for tier-recompute visit count. Stamped by apps.loyalty.services.apply_inactivity_downgrades when a customer goes 12+ months without an EARN_VISIT. After reset, recompute_tier only counts EARN_VISIT events with occurred_at > tier_reset_at — historic visits cease to contribute, so a returning customer climbs the ladder fresh.",
                null=True,
            ),
        ),
    ]
