# Generated by Django 5.2.14 on 2026-05-11 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Caller-supplied key. Should encode the operation + payload (e.g. 'webhook:max:event_id:abc123').",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional cached result of the operation. Caller stores what they want to re-return on a retry hit.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="After this timestamp the key can be re-acquired."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_keys",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency key",
                "verbose_name_plural": "Idempotency keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["expires_at"], name="tools_idemp_expires_e49229_idx"),
                    models.Index(
                        fields=["tenant", "-created_at"], name="tools_idemp_tenant__fa4d0f_idx"
                    ),
                ],
            },
        ),
    ]
