# Generated by Django 5.2.14 on 2026-05-11 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Channel slug — 'max', 'telegram', 'whatsapp', 'web'.",
                        max_length=32,
                    ),
                ),
                (
                    "channel_user_id",
                    models.CharField(
                        help_text="Stable user identifier within the channel. Stored as string for forward-compat across channels (Telegram ints, WhatsApp opaque strings, MAX numeric).",
                        max_length=128,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="E.164-normalised phone. PII — never write raw to AuditLog payload; reference by bot_user_id UUID instead.",
                        max_length=20,
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Channel-side chat identifier used by outbound send. Equal to channel_user_id in private DMs; may differ for groups.",
                        max_length=128,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name reported by the channel itself.",
                        max_length=200,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name the client typed when booking / introducing themselves. May differ from channel display_name.",
                        max_length=150,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-user scratch JSON for personalisation flags, consent timestamps, etc. Avoid raw PII — store IDs.",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        help_text="IANA timezone for time-of-day rendering in messages.",
                        max_length=64,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. Same (channel, channel_user_id) under different tenants → two distinct BotUsers by design.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bot_users",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot user",
                "verbose_name_plural": "Bot users",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-last_seen"], name="identity_bo_tenant__04e6aa_idx"
                    )
                ],
                "unique_together": {("tenant", "channel", "channel_user_id")},
            },
        ),
    ]
