# Generated by Django 5.2.14 on 2026-05-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "bot_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="client_profile",
                        serialize=False,
                        to="identity.botuser",
                    ),
                ),
                (
                    "recency_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days since last visit. NULL when no visits yet.",
                        null=True,
                    ),
                ),
                ("frequency_visits", models.IntegerField(default=0)),
                (
                    "monetary_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all visit amounts (lifetime).",
                        max_digits=12,
                    ),
                ),
                (
                    "rfm_segment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="champion | loyal | at_risk | hibernating | new (or empty pre-compute).",
                        max_length=32,
                    ),
                ),
                (
                    "ltv",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lifetime value to date. Alias for monetary_total in Phase 0; kept separate so Phase 1 LTV models can diverge from raw sum.",
                        max_digits=12,
                    ),
                ),
                (
                    "predicted_ltv_12m",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Predicted LTV over next 12 months. Phase 0 linear; Phase 1 ML.",
                        max_digits=12,
                    ),
                ),
                (
                    "churn_risk",
                    models.FloatField(
                        default=0,
                        help_text="0..1 churn score. Phase 0 heuristic from recency / avg_visit_interval; Phase 1 ML.",
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="new | active | lapsing | churned (or empty pre-compute).",
                        max_length=32,
                    ),
                ),
                (
                    "avg_visit_interval_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Average days between visits. NULL with <2 visits.",
                        null=True,
                    ),
                ),
                ("favorite_service_id", models.CharField(blank=True, default="", max_length=64)),
                ("favorite_category_id", models.CharField(blank=True, default="", max_length=64)),
                ("preferred_master_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "loyalty_tier",
                    models.CharField(
                        default="bronze",
                        help_text="bronze | silver | gold | platinum.",
                        max_length=16,
                    ),
                ),
                (
                    "last_recomputed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When recompute_profile last ran. NULL before first compute.",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — profile aggregates are derived but expensive to recompute; accidental tenant drop must not vapourise them.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client_profiles",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client profile",
                "verbose_name_plural": "Client profiles",
                "indexes": [
                    models.Index(
                        fields=["tenant", "rfm_segment"], name="identity_cl_tenant__419787_idx"
                    ),
                    models.Index(
                        fields=["tenant", "lifecycle_stage"], name="identity_cl_tenant__c99b3b_idx"
                    ),
                    models.Index(
                        fields=["tenant", "loyalty_tier"], name="identity_cl_tenant__e6f380_idx"
                    ),
                ],
            },
        ),
    ]
