"""Add ``BotUser.proactive_messages_opt_out`` (B11 conservative blockers).

P0 PRE_PILOT, founder pilot_scope_discipline sequence #3. Customer-level
opt-out flag for B11 post-visit follow-up («Как прошёл визит?») и
analogous future proactive bot-initiated messages. Default False —
existing users keep receiving B11 nudges until explicit opt-out.

### Why migration also contains «alter» operations за other models

Pre-existing model drift inherited from prior PRs (welcomed_at help_text,
MemoryEntry encryption attrs, RedZoneAccessLog AS2 enum extensions, UPC
minor_lock help). All are no-op state-sync — operations don't change
DB column shapes; only Django's internal model-state catalog. Migration
is safe против existing data.

The ONLY new schema operation is ``AddField`` для
``BotUser.proactive_messages_opt_out`` (BooleanField, default=False).
The rest is migration-state cleanup that makemigrations captures
because previous PRs landed model edits без running migration
generation.
"""

# Generated by Django 5.2.14 on 2026-05-26 20:44

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0011_botuser_consent_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userpreferences",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="userpreferences",
            new_name="identity_us_tenant__f2c68b_idx",
            old_name="identity_us_tenant__de5c0f_idx",
        ),
        migrations.RenameIndex(
            model_name="userpreferences",
            new_name="identity_us_tenant__41afa2_idx",
            old_name="identity_us_tenant__c3e9d8_idx",
        ),
        migrations.AddField(
            model_name="botuser",
            name="proactive_messages_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Customer-level opt-out of proactive bot-initiated messages (B11 post-visit follow-up etc.). False = receive.",
            ),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="welcomed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp первого успешного welcome (S1 onboarding) delivery. NULL для BotUsers до task #85 deploy.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="consent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When user explicitly consented to storing this entry. MUST be NOT NULL for sensitivity_zone IN ('yellow', 'red') before the entry is read or used — enforced by CHECK 2 + app-layer write guard. Withdrawal is NOT modeled as setting consent_at=NULL on a live row; see spec §4 for the soft-delete exemption pattern.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="content",
            field=django_cryptography.fields.encrypt(
                models.JSONField(
                    default=dict,
                    help_text="The fact payload. Encrypted at rest with the Fernet key via django-cryptography-django5 EncryptedJSONField (per ADR-0006). Red entries additionally hash-pepper'd before encryption — pepper management tracked in ADR-0011 §13.5.",
                )
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="deletion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_delete", "User-initiated per-entry delete"),
                    ("withdrawal", "Consent withdrawn for yellow/red entry"),
                    ("forget_all", "User invoked forget-all"),
                    ("ttl_purge", "Auto-purged by TTL sweep"),
                    ("minor_protection", "Auto-purged by minor-protection guard"),
                    ("unknown_legacy", "Pre-spec-era soft-delete (backfill only)"),
                ],
                help_text="Distinguishes WHY a row is being deleted. CHECK 3 enforces nullness invariant: live rows MUST have NULL; deleted rows MUST have non-NULL. unknown_legacy reserved for backfill.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="last_used_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Updated by the LLM access path (event-sourced batch, not synchronous — see spec §13.2 yellow-zone TTL sweep + ADR-0011 §6).",
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="personal_context",
            field=models.ForeignKey(
                help_text="Owning UPC. CASCADE — deleting UPC soft-deletes all entries (semantically: forget-all is a UPC-level + entries cascade soft-delete; physical CASCADE only relevant for the rare ops-level hard-delete after 30d tombstone retention).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_entries",
                to="identity.userpersonalcontext",
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="soft_deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by the soft-delete job OR in the same transaction as delete_requested_at during withdrawal. Physical purge happens 30 days later (tombstone retention per spec §5).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="source_tenant_id",
            field=models.UUIDField(
                blank=True,
                help_text="Tenant the fact originated at. NULL if cross-tenant or platform-level. Informational — NOT a scoping boundary; tenant scoping is enforced at the app-layer voice modulator + cross-tenant reuse rule per ADR-0011 §9.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memoryentry",
            name="user_id",
            field=models.UUIDField(
                db_index=True,
                help_text="Denormalised — matches personal_context.user_id. Convenience for queries that don't go through the UPC join.",
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("write", "Write"),
                    ("purge", "Purge"),
                    ("withdrawal", "Withdrawal — explicit consent revocation"),
                    (
                        "write_rejected_dob_lookup",
                        "Write rejected — DOB lookup failed (Ayla REST outage)",
                    ),
                ],
                help_text="What kind of access. Round-2 AS2 + ADR-0011 §11.3 added 'withdrawal' + 'write_rejected_dob_lookup' values.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="accessor_principal",
            field=models.CharField(
                help_text="Round-2 AS2 fix — concrete identity per accessor_role: Celery worker hostname + queue name (ayla_llm); cron job name + worker hostname (system_job); staff User.id UUID string (ops_admin); caller service-account name (future service_to_service). Indexed for staff-X-date-range auditor queries.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="accessor_role",
            field=models.CharField(
                choices=[
                    ("ayla_llm", "Ayla LLM prompt construction"),
                    ("system_job", "System job (TTL sweep, forget-all)"),
                    ("ops_admin", "Ops admin (break-glass)"),
                ],
                help_text="Coarse category. Round-2 AS2: insufficient alone for 152-ФЗ Chapter 3 «who accessed» — accessor_principal carries the concrete identity.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="memory_entry_id",
            field=models.UUIDField(
                help_text="The entry being accessed. NOT a Django FK with CASCADE — log rows persist after entry purge. Migration uses RunSQL to add raw FK with ON DELETE NO ACTION."
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="purpose",
            field=models.TextField(
                help_text="Human-readable purpose (round-3 A5): 'contraindication_check', 'subject_access_request', 'incident_debug', 'ttl_sweep', etc."
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="request_id",
            field=models.UUIDField(
                help_text="Audit reference — Celery task id, HTTP request id, OR ops ticket id. Validated as UUID by the BEFORE SELECT trigger (spec §9). Round-3 A5: MUST be a real audit reference, not arbitrary string."
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="forget_all_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when user invokes POST /api/v1/users/me/memory/forget-all (per ADR-0011 §3.3). Records user-intent moment; async sweep then soft-deletes all entries.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="minor_lock",
            field=models.BooleanField(
                default=False,
                help_text="Per ADR-0011 §10.2 + spec §1: set true when reconciliation job detects post-fact that the user is a minor; blocks future yellow/red writes via the writer guard. Reconciliation job tracked in issue #597.",
            ),
        ),
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Ayla's running summary of who this user is. Application-side capped at 8 KB. NOT encrypted at storage layer because it's intentionally retrievable in plaintext by the LLM context-building path on every conversation.",
                null=True,
            ),
        ),
    ]
