# Generated by Django 5.2.14 on 2026-08-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0014_seed_global_bot_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryentry",
            name="consent_scope",
            field=models.CharField(
                blank=True,
                help_text="CSR scope that AUTHORIZED the write of this entry (§3.1; MVP: preference_memory). Attribute of the write — never rewritten on read/use. Nullable for the transition period; backfill per migration plan.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="derivation_method",
            field=models.CharField(
                blank=True,
                help_text="How the fact was derived (§3.1; for confirmed inference). NULL for user_stated facts.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="effective_from",
            field=models.DateTimeField(
                blank=True,
                help_text="When the fact starts being effective (§3.1). NULL on legacy rows until the Step-3 backfill (= created_at).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="evidence_refs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="References to observations (messages/events) the fact was confirmed from (§3.1). Callable default — never a shared mutable [].",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Absolute expiry moment (§3.1). ttl_days stays the relative policy input; expires_at = created_at + ttl_days is computed by the Step-3 backfill, not here.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="purpose_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Allowed usage purposes restricting retrieval (§3.1). [] = inherit from category policy. Resolver enforcement is a later step — not implemented here.",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="source_event_id",
            field=models.UUIDField(
                blank=True,
                help_text="Idempotency key — the originating event (§3.1). Unique where NOT NULL; Postgres unique allows multiple NULLs.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("superseded", "Superseded by a newer entry"),
                    ("expired", "Expired"),
                    ("deletion_pending", "Deletion requested, tombstone pending"),
                    ("deleted", "Deleted (soft)"),
                ],
                default=None,
                help_text="Lifecycle status per §3.1. NULL on legacy rows until the Step-3 backfill; runtime logic does not read it yet.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The entry this one was superseded by (§3.1, §6 immutable supersession). SET_NULL: purging the replacement never cascades onto the superseded row.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="identity.memoryentry",
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="supersession_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corrected", "Corrected — the old value was wrong"),
                    ("changed", "Changed — the fact legitimately changed"),
                    ("consolidated", "Consolidated into another entry"),
                    ("policy_migration", "Policy-driven migration"),
                ],
                help_text="Why the entry was superseded (§3.1). Required when status=superseded (app-level, Step 3+); supersession is NOT a deletion_reason.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="memoryentry",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last state-transition moment (§3.1). NOT auto_now — existing save paths must not start touching it implicitly. NULL on legacy rows until the Step-3 backfill (= created_at). Distinct from last_used_at (usage tracking).",
                null=True,
            ),
        ),
    ]
