# Generated by Django 5.2.14 on 2026-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0016_memoryentry_step3_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryentry",
            name="provenance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_stated", "User stated directly"),
                    (
                        "user_confirmed_inference",
                        "Inference explicitly confirmed by the user",
                    ),
                ],
                default=None,
                help_text="Canonical provenance per §3.1 (Step 2.5 schema correction). The legacy `source` field is NOT re-purposed: explicit→user_stated backfill is Step 3B (migration 0018); inferred/signal rows stay NULL — user_confirmed_inference requires explicit confirmation via the proposal flow.",
                max_length=30,
                null=True,
            ),
        ),
    ]
