# Generated by Django 5.2.14 on 2026-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0020_drop_userpreferences_allergies"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="blocked_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Когда клиента заблокировали из админки (DRF-1497). NULL = не заблокирован. Non-null = исходящие ему не отправляются.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="blocked_by_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто заблокировал (username учётной записи админки). Дублирует журнал, чтобы карточка читалась без второго запроса.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="blocked_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Причина блокировки — обязательна, см. apps.identity.services.blocking. Показывается в карточке клиента.",
                max_length=500,
            ),
        ),
    ]
