# Generated by Django 5.2.14 on 2026-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0023_timezone_unset_is_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="ayla_user_id_is_proxy",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Sort of the Ayla account `ayla_user_id` points at: False = a real bound account, True = Ayla's isolated proxy, NULL = unknown (written by a path that does not learn it, or predates this column). Written in the same save() as the key by apps/identity/services/ayla_link.py — a sort that could be filled in separately would create a fourth state, 'key present, sort pending', worse than any of the three.",
                null=True,
                verbose_name="Ключ Ayla — прокси",
            ),
        ),
    ]
