# Generated by Django 5.2.14 on 2026-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0024_drf1649_ayla_user_id_is_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpersonalcontext",
            name="deletion_request_id",
            field=models.UUIDField(
                blank=True,
                help_text="Catalog DeletionRequest id the person saw on screen.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpersonalcontext",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the person's account-deletion request was accepted (§7). Personalisation stops.",
                null=True,
            ),
        ),
    ]
