# Generated by Django 5.2.14 on 2026-09-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0024_drf1649_ayla_user_id_is_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="customer_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не записано"),
                    ("client_bot", "Клиентский контур"),
                    ("salon_assistant", "Салонный помощник"),
                ],
                default="",
                help_text="§2.3: where this relationship came from. SALON_ASSISTANT is required on a SHADOW; CLIENT_BOT is the client contour's own shell.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="customer_status",
            field=models.CharField(
                choices=[
                    ("unresolved", "Правило §2 не применялось"),
                    ("linked", "Связан с профилем клиента Ayla"),
                    ("shadow", "Теневой профиль салонного помощника"),
                ],
                db_index=True,
                default="unresolved",
                help_text="§2: LINKED — matched to the client contour by MAX ID, an identity link or a confirmed phone; SHADOW — none of those, a restricted profile the salon assistant created; UNRESOLVED — the rule was not applied yet (never a permission).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="customer_status_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When customer_status was last decided. NULL exactly while UNRESOLVED: a status with no moment is a guess, not a decision.",
                null=True,
            ),
        ),
    ]
