# Generated by Django 5.2.17 on 2026-09-12 02:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_schedule_confirmation"),
        ("identity", "0026_drf1699_deletion_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoloIdentityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTITY_LINK_PENDING", "Ожидает связывания"),
                            ("IDENTITY_LINKED", "Связан"),
                            ("IDENTITY_LINK_REJECTED", "Отклонено"),
                        ],
                        default="IDENTITY_LINK_PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPERATOR_VERIFIED", "Проверил оператор"),
                            ("CATALOG_RESOLVED", "Каталог ответил настоящим ключом"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "solo_registration_id",
                    models.UUIDField(
                        help_text="id тенанта соло-мастера — регистрация одна на тенант."
                    ),
                ),
                ("channel", models.CharField(max_length=16)),
                ("channel_user_id", models.CharField(max_length=128)),
                ("tenant_id_snapshot", models.UUIDField()),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="auth.User.pk оператора в админке бота (int, как LogEntry.user_id).",
                        null=True,
                    ),
                ),
                (
                    "operator_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ayla_user_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Что записано в CatalogMaster.ayla_user_id в момент LINKED.",
                        null=True,
                    ),
                ),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_a_master", "Не мастер"),
                            ("duplicate_person", "Уже есть аккаунт мастера"),
                            ("identity_unverifiable", "Личность не подтверждена"),
                            ("fraud_suspected", "Подозрение на злоупотребление"),
                            ("other", "Другое (в комментарии)"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "reject_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "last_attempt_refusal",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Машинная причина последнего отказа автосвязи (solo_link_attempt).",
                        max_length=64,
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "master",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_link",
                        to="catalog.catalogmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь соло-мастера с Ayla",
                "verbose_name_plural": "Связи соло-мастеров с Ayla",
                "indexes": [models.Index(fields=["status"], name="solo_identity_link_status_idx")],
            },
        ),
    ]
