# Generated by Django 5.2.17 on 2026-09-12 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0027_drf1695_solo_identity_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoloRegistrationDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=16)),
                ("channel_user_id", models.CharField(max_length=128)),
                ("chat_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("name", "Ждём имя"),
                            ("city", "Ждём город"),
                            ("confirm", "Ждём подтверждение"),
                        ],
                        default="name",
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Черновик регистрации соло-мастера",
                "verbose_name_plural": "Черновики регистрации соло-мастеров",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "channel_user_id"),
                        name="solo_registration_draft_one_per_identity",
                    )
                ],
            },
        ),
    ]
