# Generated by Django 5.2.17 on 2026-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0028_drf1793_solo_registration_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="soloidentitylink",
            name="catalog_provisioned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда каталог подтвердил solo-workspace (readback ответа), не когда послали.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soloidentitylink",
            name="catalog_provisioning_refusal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Машинная причина последнего неуспешного провижининга в каталоге; пусто после успеха.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="soloidentitylink",
            name="catalog_specialist_id",
            field=models.UUIDField(
                blank=True,
                help_text="SpecialistProfile.id DRAFT-профиля, заведённого в каталоге для этого workspace.",
                null=True,
            ),
        ),
    ]
