# Generated by Django 5.2.17 on 2026-09-15 21:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0029_drf1830_solo_catalog_provisioning_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="AylaErasureJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ayla_user_id", models.UUIDField(verbose_name="Субъект в Ayla")),
                (
                    "external_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Внешний идентификатор для повтора",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "revoke_data_storage",
                                "Отзыв согласия на хранение данных",
                            ),
                            ("personal_data_delete", "Удаление персональных данных"),
                            ("chat_forget", "«Забудь всё» в чате"),
                        ],
                        max_length=32,
                        verbose_name="Откуда запрос",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("completed", "Стирание подтверждено"),
                            ("failed", "Повторы исчерпаны"),
                            (
                                "superseded_by_account_deletion",
                                "Закрыто удалением аккаунта",
                            ),
                        ],
                        default="pending",
                        max_length=40,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Следующая попытка"),
                ),
                (
                    "last_error_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Последняя причина",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Закрыто"),
                ),
                (
                    "alerted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Алерт отправлен"),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.botuser",
                        verbose_name="Пользователь бота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание удаления в Ayla",
                "verbose_name_plural": "Задания удаления в Ayla",
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="ayla_erasure_job_due",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("ayla_user_id",),
                        name="ayla_erasure_job_one_pending_per_subject",
                    )
                ],
            },
        ),
    ]
