# Generated by Django 5.2.14 on 2026-09-19 23:28
#
# DRF-2133 — choices-only. Схема БД не меняется (CharField без DB-CHECK на
# choices): добавлены роль accessor ``data_subject``, тип доступа ``delete``
# и причина удаления ``user_request_miniapp`` для экрана «Что Ayla помнит».

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0030_ayla_erasure_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryentry",
            name="deletion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_delete", "User-initiated per-entry delete"),
                    (
                        "user_request_miniapp",
                        "User-initiated per-entry delete from Mini App",
                    ),
                    ("withdrawal", "Consent withdrawn for yellow/red entry"),
                    ("forget_all", "User invoked forget-all"),
                    ("ttl_purge", "Auto-purged by TTL sweep"),
                    ("minor_protection", "Auto-purged by minor-protection guard"),
                    ("unknown_legacy", "Pre-spec-era soft-delete (backfill only)"),
                ],
                help_text="Distinguishes WHY a row is being deleted. CHECK 3 enforces nullness invariant: live rows MUST have NULL; deleted rows MUST have non-NULL. unknown_legacy reserved for backfill.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("write", "Write"),
                    ("purge", "Purge"),
                    ("delete", "Delete — subject-requested soft-delete (tombstone)"),
                    ("withdrawal", "Withdrawal — explicit consent revocation"),
                    (
                        "write_rejected_dob_lookup",
                        "Write rejected — DOB lookup failed (Ayla REST outage)",
                    ),
                ],
                help_text="What kind of access. Round-2 AS2 + ADR-0011 §11.3 added 'withdrawal' + 'write_rejected_dob_lookup' values; DRF-2133 added 'delete' (subject-requested soft-delete from the Mini App).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="accessor_role",
            field=models.CharField(
                choices=[
                    ("ayla_llm", "Ayla LLM prompt construction"),
                    ("system_job", "System job (TTL sweep, forget-all)"),
                    ("ops_admin", "Ops admin (break-glass)"),
                    ("data_subject", "Data subject (own memory, Mini App)"),
                ],
                help_text="Coarse category. Round-2 AS2: insufficient alone for 152-ФЗ Chapter 3 «who accessed» — accessor_principal carries the concrete identity.",
                max_length=20,
            ),
        ),
    ]
