# Generated by Django 5.2.17 on 2026-09-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0031_drf2133_data_subject_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="block_notice_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда этой строке сказали фразу блокировки (DRF-2276). Служебная метка «раз за эпизод», не факт о человеке.",
                null=True,
            ),
        ),
    ]
