# Generated by Django 5.2.14 on 2026-09-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0032_drf2276_block_notice_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botuser",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Avatar URL mirrored from Ayla user.profile.updated event (per event-contract.md §3.12). Kept for personal-data accounting and erasure only — NOT returned by any endpoint and NOT rendered (DRF-2520): it is an internal public-read storage URL. NOT a canonical store — Ayla djangoproject is. Refresh via REST GET /api/v1/users/{ayla_user_id} on event receipt. Empty string default for backward compat.",
                max_length=500,
            ),
        ),
    ]
