# Generated by Django 5.2.14 on 2026-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0032_drf2276_block_notice_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpersonalcontext",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Reserved; nothing writes it (DRF-2526). A prose summary of the person is inference, and inference reaches persistent memory only via MemoryProposal (AYLA-DEC-0024). Forget-all sets it to NULL. Readers treat blank as absent; if ever filled, the prompt builder reads it in plaintext, verbatim, with no provenance.",
                null=True,
            ),
        ),
    ]
