# Generated by Django 5.2.14 on 2026-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0034_drf2520_avatar_url_not_rendered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="access_type",
            field=models.CharField(
                choices=[
                    ("read", "Read"),
                    ("write", "Write"),
                    ("purge", "Purge"),
                    ("delete", "Delete — subject-requested soft-delete (tombstone)"),
                    ("withdrawal", "Withdrawal — explicit consent revocation"),
                    (
                        "write_rejected_dob_lookup",
                        "Write rejected — DOB lookup failed (Ayla REST outage)",
                    ),
                    (
                        "write_rejected_no_consent",
                        "Write rejected — yellow/red without consent (DB CHECK)",
                    ),
                ],
                help_text="What kind of access. Round-2 AS2 + ADR-0011 §11.3 added 'withdrawal' + 'write_rejected_dob_lookup' values; DRF-2133 added 'delete' (subject-requested soft-delete from the Mini App).",
                max_length=32,
            ),
        ),
    ]
