# Generated by Django 5.2.14 on 2026-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0035_drf2542_access_type_no_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryentry",
            name="source_tenant_id",
            field=models.UUIDField(
                blank=True,
                help_text="Tenant the fact was said at, resolved at write time (DRF-2544): the salon in scope, or the global_bot sentinel for the global surface. NULL = origin UNKNOWN (rows before DRF-2544, or a path that declared neither) — NOT «platform-level». Read rule: personal_fields.UNKNOWN_ORIGIN_NEVER_CROSSES.",
                null=True,
            ),
        ),
    ]
