# Generated by Django 5.2.17 on 2026-10-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0037_drf2774_access_type_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redzoneaccesslog",
            name="accessor_role",
            field=models.CharField(
                choices=[
                    ("ayla_llm", "Ayla LLM prompt construction"),
                    ("system_job", "System job (TTL sweep, forget-all)"),
                    ("ops_admin", "Ops admin (break-glass)"),
                    ("data_subject", "Data subject (own memory, Mini App)"),
                    ("recommendations", "Recommendations filter (allergen exclusion)"),
                    ("scanner", "Food scanner (allergen warning)"),
                ],
                help_text="Coarse category. Round-2 AS2: insufficient alone for 152-ФЗ Chapter 3 «who accessed» — accessor_principal carries the concrete identity.",
                max_length=20,
            ),
        ),
    ]
