# Generated by Django 5.2.17 on 2026-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0038_drf2132_accessor_roles_recommendations_scanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpersonalcontext",
            name="declared_fields_withheld",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="DRF-2700: имена полей анкеты Ayla, которые человек попросил забыть, а очистить в анкете нельзя (у контракта нет значения «пусто» для цены). Такое поле из анкеты не читается, пока человек не назовёт его заново. Только имена, без значений.",
            ),
        ),
        migrations.AddField(
            model_name="userpersonalcontext",
            name="model_history_cutoff_at",
            field=models.DateTimeField(
                blank=True,
                help_text="DRF-2700: момент последнего поштучного «забудь X». Реплики не позже него модели не отдаются; человек их видит как прежде. Только время, без содержания стёртого. Только растёт.",
                null=True,
            ),
        ),
    ]
