# Generated by Django 5.2.14 on 2026-05-11 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0003_alter_conversation_bot_user"),
        ("identity", "0001_initial"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("handoff", "Handoff"),
                            ("complaint", "Complaint"),
                            ("medical_red_flag", "Medical red flag"),
                            ("manual", "Manual"),
                        ],
                        help_text="Why the task exists. See TaskType for the 4 Phase-0 categories.",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Operator-queue priority. MEDICAL_RED_FLAG ships URGENT; COMPLAINT ships HIGH; HANDOFF ships NORMAL by default.",
                        max_length=16,
                    ),
                ),
                (
                    "transcript_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen messages + ClientProfile snapshot at the moment of creation. Filled by the C2 packager. Even if the underlying Conversation grows after handoff, this dict reflects the operator's starting context.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="OPEN → IN_PROGRESS → RESOLVED|CANCELLED. Transitions formalised in C3 handoff services; admin UI flips this.",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why the bot triggered the handoff. Free-form. Operator-facing.",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Operator's note on resolve / cancel. Forensic + customer-service trail.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped on the {OPEN, IN_PROGRESS} → RESOLVED transition. NULL for OPEN/IN_PROGRESS/CANCELLED rows.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operator working on this task. NULL while in OPEN. SET_NULL on user departure keeps the task in the queue for reassign.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_admin_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        help_text="The user whose conversation triggered the handoff. PROTECT so soft-delete on the user (Sprint 2.5 H1) keeps the forensic task intact.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_tasks",
                        to="identity.botuser",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation snapshot anchor. PROTECT — handoff tasks survive conversation cleanup.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_tasks",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant the task belongs to. PROTECT so accidental tenant delete cannot vapourise open operator queues.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_tasks",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin task",
                "verbose_name_plural": "Admin tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="handoff_adm_tenant__ce8536_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"], name="handoff_adm_assigne_aa2900_idx"
                    ),
                ],
            },
        ),
    ]
