# Generated by Django 5.2.14 on 2026-09-05 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0016_conversation_anonymized_reason_and_more"),
        ("handoff", "0001_admintask"),
        ("identity", "0020_drop_userpreferences_allergies"),
        ("tenancy", "0012_alter_tenantstaff_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoffSilenceNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Channel chat the notices go to. Stored rather than re-derived: the release message is sent long after the inbound turn that carried it.",
                        max_length=64,
                    ),
                ),
                (
                    "announced_here",
                    models.BooleanField(
                        default=False,
                        help_text="True when the handoff confirmation was delivered in THIS dialog. Picks which of the two silence wordings the person reads.",
                    ),
                ),
                (
                    "silence_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the person was told the bot is muted. NULL = not yet; non-NULL = never again for this episode.",
                        null=True,
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the mute lifted and the person was told the bot is back. NULL marks the one open episode for this conversation.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Handoff silence notice",
                "verbose_name_plural": "Handoff silence notices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="admintask",
            name="assigned_queue",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Duty queue the task is addressed to when no named operator was resolvable (DRF-1488). Empty together with `assigned_to` means the task reached nobody — a configuration error, not a state.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an operator actually took the task (assigned_to set). NULL = still waiting in the queue; the pickup sweep measures the wait from `created_at` to this.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="pickup_escalated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped ONCE by the pickup sweep when nobody claimed the task within HANDOFF_PICKUP_SLA_MINUTES. Non-NULL is what makes the escalation fire exactly once.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="admintask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Named operator working on this task. NULL means the task is addressed to `assigned_queue` instead and still waits for someone to pick it up. SET_NULL on user departure drops the task back to its queue rather than losing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_admin_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="admintask",
            index=models.Index(fields=["status", "created_at"], name="handoff_task_status_age_idx"),
        ),
        migrations.AddField(
            model_name="handoffsilencenotice",
            name="bot_user",
            field=models.ForeignKey(
                help_text="Whose dialog it is. Carries channel + channel_user_id, which is how the release check re-asks «is this person still being served by a human?».",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handoff_silence_notices",
                to="identity.botuser",
            ),
        ),
        migrations.AddField(
            model_name="handoffsilencenotice",
            name="conversation",
            field=models.ForeignKey(
                help_text="The dialog that went silent. PROTECT for the same reason AdminTask.conversation is PROTECT — this is forensic evidence.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handoff_silence_notices",
                to="conversations.conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="handoffsilencenotice",
            index=models.Index(
                fields=["bot_user", "released_at"],
                name="handoff_han_bot_use_73508f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="handoffsilencenotice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("conversation",),
                name="handoff_one_open_silence_notice_per_conversation",
            ),
        ),
    ]
