# Generated by Django 5.2.14 on 2026-09-05 08:04

import apps.adminconsole.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("handoff", "0001_admintask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDataAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("granted", "доступ открыт"),
                            ("opened", "экран открыт"),
                            ("denied", "отказано"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                (
                    "actor_pk",
                    models.CharField(
                        blank=True,
                        help_text="Первичный ключ учётной записи строкой — ссылки нет намеренно, запись переживает отзыв учётки.",
                        max_length=64,
                    ),
                ),
                (
                    "screen",
                    models.CharField(
                        blank=True,
                        help_text="`<app_label>.<model>` открытого экрана. Пусто — когда строка про выдачу пропуска, а не про открытый экран.",
                        max_length=120,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=200)),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("client_label", models.CharField(blank=True, max_length=200)),
                ("tenant_slug", models.CharField(blank=True, max_length=100)),
                ("admin_task_id", models.UUIDField(blank=True, null=True)),
                ("grant_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        help_text="Почему отказано — человеческим языком, тот же текст, что увидел отказанный.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал доступа к данным клиента",
                "verbose_name_plural": "Журнал доступа к данным клиента",
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["client_id", "occurred_at"],
                        name="acc_log_client_at_idx",
                    ),
                    models.Index(
                        fields=["actor_username", "occurred_at"],
                        name="acc_log_actor_at_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClientDataAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=150,
                        verbose_name="Имя автора",
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        editable=False,
                        help_text="identity.BotUser.id — берётся из обращения.",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "client_label",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Клиент (как показывать)",
                    ),
                ),
                (
                    "tenant_slug",
                    models.CharField(
                        blank=True, editable=False, max_length=100, verbose_name="Салон"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Зачем открываете переписку и профиль. Причина попадает в журнал доступа и читается человеком, а не машиной.",
                        validators=[apps.adminconsole.models.validate_reason],
                        verbose_name="Причина просмотра",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(editable=False, verbose_name="Действует до"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        editable=False,
                        help_text="Пропуск живёт часами; удаление учётной записи гасит его вместе с ней. След остаётся в журнале доступа.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто открыл",
                    ),
                ),
                (
                    "admin_task",
                    models.ForeignKey(
                        help_text="Задача из очереди handoff, с которой вы работаете. Клиент и салон берутся из неё — вручную их выбрать нельзя.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="handoff.admintask",
                        verbose_name="Обращение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к данным клиента",
                "verbose_name_plural": "Доступ к данным клиента",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["actor", "expires_at"], name="acc_grant_actor_exp_idx")
                ],
            },
        ),
    ]
