# Generated by Django 5.2.14 on 2026-05-11 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Source channel (max, telegram, web, ...).", max_length=40
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(
                        help_text="Channel-supplied unique event id (idempotency hint).",
                        max_length=200,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full untouched webhook payload. Preserved for replay (Sprint 5).",
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Correlates with downstream stream + worker events.",
                        max_length=64,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the consumer XACKs the matching stream entry.",
                        null=True,
                    ),
                ),
                (
                    "resolved_tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant the channel token resolved to. Null if unknown.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhook_journal",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook journal",
                "verbose_name_plural": "Webhook journal",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["resolved_tenant", "-received_at"],
                        name="ingress_web_resolve_caa010_idx",
                    ),
                    models.Index(fields=["trace_id"], name="ingress_web_trace_i_a9716f_idx"),
                    models.Index(
                        fields=["channel", "-received_at"], name="ingress_web_channel_0af8d3_idx"
                    ),
                    models.Index(fields=["processed_at"], name="ingress_web_process_64a505_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "external_event_id"), name="ingress_journal_dedup"
                    )
                ],
            },
        ),
    ]
