# Generated by Django 5.2.17 on 2026-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookjournal",
            name="raw_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Тело вебхука для разбора инцидентов; живёт INGRESS_RAW_RETENTION_HOURS. Содержимое аудио-вложений (ссылка на запись голосового) сюда не пишется (DRF-1943).",
            ),
        ),
    ]
