# Generated by Django 5.2.14 on 2026-05-11 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandVoiceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        default="friendly",
                        help_text="Placeholder for Sprint 2 — replaced by structured tone fields in Sprint 4.",
                        max_length=100,
                    ),
                ),
                (
                    "voice_examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="In-context learning samples for the LLM. Sprint 4 populates from the operator's tone-of-voice guide.",
                    ),
                ),
                (
                    "disclaimers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-tenant legal / safety wording attached to responses. Sprint 4 populates from operator config.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="The tenant this configuration belongs to. CASCADE — if a tenant is hard-deleted (rare; usually deactivated), its persona config goes too.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_voice",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand voice configuration",
                "verbose_name_plural": "Brand voice configurations",
            },
        ),
    ]
