# Generated by Django 5.2.14 on 2026-05-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0001_initial"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandvoiceconfig",
            name="tenant",
            field=models.OneToOneField(
                help_text="The tenant this configuration belongs to. PROTECT for consistency with every other Tenant FK in the platform (audit/events/conversations/messages/bot_users/idempotency/webhooks). Tenant deletes are an operational event blocked by design — soft-deactivate via Tenant.is_active=False instead.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brand_voice",
                to="tenancy.tenant",
            ),
        ),
    ]
