# Generated by Django 5.2.14 on 2026-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persona", "0002_alter_brandvoiceconfig_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandvoiceconfig",
            name="forbidden_phrases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of regex patterns. C4 voice_check validates outbound text against these and emits `safety_triggered` on match.",
            ),
        ),
        migrations.AddField(
            model_name="brandvoiceconfig",
            name="persona",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured persona: {"name": "Alina", "role": "consultant", "age": 32, "traits": ["warm", "professional"]}. Sprint 4 ships the schema; Phase 1 wires it through `ayla-ai-core` voice utils.',
            ),
        ),
        migrations.AddField(
            model_name="brandvoiceconfig",
            name="tone_modulations",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Conditional tone overrides by context. Example: {"risk_level=high": {"formality": 0.9, "warmth": 0.4}, "sentiment=frustrated": {"warmth": 0.95}}.',
            ),
        ),
        migrations.AddField(
            model_name="brandvoiceconfig",
            name="tone_vector",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Numeric tone axes 0..1: {"warmth": 0.8, "formality": 0.5, "energy": 0.6}. LLM prompt composition reads these to bias style.',
            ),
        ),
        migrations.AddField(
            model_name="brandvoiceconfig",
            name="version",
            field=models.IntegerField(
                default=1,
                help_text="Bumped on every operator save — loaders use it as the cache key tail so config changes invalidate without explicit pub/sub plumbing.",
            ),
        ),
        migrations.AlterField(
            model_name="brandvoiceconfig",
            name="disclaimers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sprint 2 placeholder. Sprint 4 / A3 moved per-tenant disclaimers into `apps.promptreg.DisclaimerLibrary` — this field is dead weight kept for back-compat; cleanup in Sprint 5.",
            ),
        ),
        migrations.AlterField(
            model_name="brandvoiceconfig",
            name="tone",
            field=models.CharField(
                default="friendly",
                help_text="Sprint 2 placeholder — kept for backward compat. Sprint 4+ readers should use the structured `tone_vector` JSON.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="brandvoiceconfig",
            name="voice_examples",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="In-context learning samples for the LLM (populated Sprint 4 / C1).",
            ),
        ),
    ]
