# Generated by Django 5.2.14 on 2026-05-11 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(
                        help_text="Skill this prompt belongs to (e.g. 'privacy_consent', 'human_handoff', 'faq'). Matches the Skill.name ClassVar.",
                        max_length=64,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The prompt text — Jinja2-style placeholders allowed; the orchestrator interpolates at call time."
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Monotonic per-skill version number. Operator-assigned at create time; uniqueness enforced by Meta.unique_together."
                    ),
                ),
                (
                    "traffic_percent",
                    models.IntegerField(
                        default=100,
                        help_text="Canary rollout percentage [0-100]. Sprint 4+ experiment framework gates traffic to this version by bucketed hash. Default 100 means: when active, all traffic goes here.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="True iff this version is the currently-served prompt for its (tenant, skill_name). Exactly ONE row per pair has this set; publish_prompt (A4) enforces the invariant atomically.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped by publish_prompt at the moment of activation. NULL while the version sits in draft.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Operator who authored this revision. PROTECT so a user-account delete cannot vapourise the audit trail.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — accidental tenant delete must not vapourise the prompt library that bot behaviour depends on.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prompt_versions",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt version",
                "verbose_name_plural": "Prompt versions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "skill_name", "is_active"],
                        name="promptreg_p_tenant__c8dc7e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "skill_name", "version"),
                        name="promptreg_promptversion_unique_tenant_skill_version",
                    )
                ],
            },
        ),
    ]
