# Generated by Django 5.2.14 on 2026-05-11 16:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptreg", "0001_promptversion"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThresholdConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Threshold identifier — by convention snake_case noun.",
                        max_length=64,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Numeric value. Decimal not float — exactness matters when operators tune to 0.65 etc.",
                        max_digits=10,
                    ),
                ),
                (
                    "applied_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Skill name the threshold applies to. Empty string ("") = global / fallback.',
                        max_length=64,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Monotonic per (tenant, key, applied_to). Lets operators publish a new value without losing the old.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Currently-served threshold. Default True (different from PromptVersion which defaults False) — most threshold edits are in-place tuning rather than canary rollouts.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threshold_configs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threshold config",
                "verbose_name_plural": "Threshold configs",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "key", "applied_to", "is_active"],
                        name="promptreg_t_tenant__2fa965_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "key", "applied_to", "version"),
                        name="promptreg_threshold_unique_tenant_key_applied_version",
                    )
                ],
            },
        ),
    ]
