# Generated by Django 5.2.14 on 2026-05-11 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptreg", "0002_thresholdconfig"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisclaimerLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("pricing", "Pricing"),
                            ("aftercare", "Aftercare"),
                            ("booking", "Booking"),
                            ("general", "General"),
                        ],
                        help_text="Disclaimer category. Free-text-with-suggested-choices: Sprint 4 ships 5 categories, operators may extend without migration.",
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        help_text="Audience-of-this-disclaimer severity. Skills pick the matching level by topic risk.",
                        max_length=8,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The disclaimer text. Markdown allowed; channel adapter strips on the way out."
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Monotonic per (tenant, category, risk_level)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Currently-served disclaimer. Default True — disclaimers are written deliberately; the operator publishes immediately.",
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the operator retires this disclaimer entirely (distinct from is_active=False which is just 'not current').",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disclaimers",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disclaimer",
                "verbose_name_plural": "Disclaimers",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "category", "risk_level", "is_active"],
                        name="promptreg_d_tenant__3519cf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "category", "risk_level", "version"),
                        name="promptreg_disclaimer_unique_tenant_cat_risk_version",
                    )
                ],
            },
        ),
    ]
