# Generated by Django 5.2.14 on 2026-05-13 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0004_tenant_shadow_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowDeltaSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True,
                        help_text="The UTC date the delta was computed for. The S4 task schedules at 08:00 МСК and reads yesterday's shadow rows.",
                    ),
                ),
                (
                    "intent_agreement",
                    models.FloatField(
                        default=0.0,
                        help_text="0..1. % of shadow Message rows whose intent matched mysite ground truth.",
                    ),
                ),
                (
                    "action_type_agreement",
                    models.FloatField(
                        default=0.0,
                        help_text="0..1. % match on action_type. Captures handoff drift.",
                    ),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of (shadow, ground-truth) pairs that matched the join keys. Zero = missing CSV or no shadow traffic.",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full DeltaSummary serialisation. Includes latency p50/p95 deltas, error_delta_pct, and any debug fields S5 needs.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — a dropped tenant's history is forensic data + a billing/legal incident path.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shadow_delta_snapshots",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shadow delta snapshot",
                "verbose_name_plural": "Shadow delta snapshots",
                "ordering": ["-snapshot_date", "tenant"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-snapshot_date"], name="observabili_tenant__1129e5_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "snapshot_date"),
                        name="shadow_delta_one_per_tenant_per_day",
                    )
                ],
            },
        ),
    ]
