# Generated by Django 5.2.14 on 2026-05-26 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_conversation_last_payment_event_id"),
        ("identity", "0011_botuser_consent_at"),
        ("observability", "0001_initial"),
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequestMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the AI request finished. Drives the daily aggregation cursor (Веха 2) — rollup pulls rows for `date(created_at) == target_date`.",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Trace correlation ID — matches the orchestrator's trace_id_scope() so a single user turn can be reconstructed across logs + Event rows + this metric. Indexed for «show me everything for trace X» queries.",
                    ),
                ),
                (
                    "message_text_length",
                    models.IntegerField(
                        help_text="Length of the inbound user message text in characters. Stored separately from message body (which lives in Conversation + Message rows) so cost-vs-length analysis doesn't require joining."
                    ),
                ),
                (
                    "intent_classified",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="The intent label the classifier produced (e.g. 'book_service', 'ask_master_availability'). Empty when no classifier ran (e.g. early fallback). Indexed for per-intent aggregation in Веха 2.",
                        max_length=64,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="0..1 classifier confidence. NULL when no classifier ran. Drives the fallback-trigger threshold (BeautyGo Tier-A #4 — confidence < 0.7).",
                        null=True,
                    ),
                ),
                (
                    "skill_selected",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The skill registry name that handled the request (e.g. 'booking', 'faq', 'echo'). Empty on early fallback / error before dispatch.",
                        max_length=64,
                    ),
                ),
                (
                    "fallback_triggered",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the skill dispatcher chose clarification over execution (confidence below threshold OR no skill matched). Drives the Fallback Rate threshold metric (< 20% target).",
                    ),
                ),
                (
                    "latency_total_ms",
                    models.IntegerField(
                        help_text="Total wall-clock time from request receipt to outbound dispatch, in milliseconds. Drives the Latency p95 < 3000ms threshold."
                    ),
                ),
                (
                    "latency_llm_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="LLM API call duration in ms (subset of latency_total). NULL when no LLM call (cached / non-LLM skill path).",
                        null=True,
                    ),
                ),
                (
                    "latency_skill_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Skill execute() duration in ms (subset of latency_total). NULL on early fallback / error before skill dispatch.",
                        null=True,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="LLM provider slug — 'openai', 'anthropic', 'yandex', etc. Empty when no LLM call. Used for per-provider cost breakdown.",
                        max_length=32,
                    ),
                ),
                (
                    "llm_tokens_input",
                    models.IntegerField(
                        blank=True,
                        help_text="Input tokens billed by the provider. NULL when no LLM call.",
                        null=True,
                    ),
                ),
                (
                    "llm_tokens_output",
                    models.IntegerField(
                        blank=True,
                        help_text="Output tokens billed by the provider. NULL when no LLM call.",
                        null=True,
                    ),
                ),
                (
                    "llm_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="USD cost for this single LLM call (6 dp = 0.000001 = a fraction of a cent). Drives the Cost per Request < $0.01 threshold. NULL when no LLM call.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success — AI handled the request end-to-end"),
                            ("error", "Error — exception during skill / LLM execution"),
                            ("fallback", "Fallback — confidence < threshold, asked clarification"),
                            ("escalated", "Escalated — handed off to human operator"),
                        ],
                        db_index=True,
                        help_text="Terminal state of the AI handling: success / error / fallback / escalated. Drives the Task Success Rate heuristic via correlation with downstream booking events (filled by Веха 2 aggregation job).",
                        max_length=16,
                    ),
                ),
                (
                    "booking_event_id",
                    models.UUIDField(
                        blank=True,
                        help_text="If a booking event landed within 60 min of this AI message in the same conversation, the daily aggregation job (Веха 2) records the booking event's id here. Drives Task Success Rate (heuristic). NULL until correlated.",
                        null=True,
                    ),
                ),
                (
                    "success_correlated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the aggregation job linked this row to a booking event. NULL until correlated. Lets late-arriving aggregation distinguish «not yet checked» from «checked, no correlation found».",
                        null=True,
                    ),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose message triggered the AI request. PROTECT to preserve metric history; nullable for system-triggered AI calls (e.g. proactive nudges, scheduled retention messages).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_request_metrics",
                        to="identity.botuser",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning conversation. SET_NULL — Conversation soft-deletes are common (152-ФЗ forget-flow); metric row survives for billing/audit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_request_metrics",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — metric history is forensic + billing-adjacent data; dropping a tenant must not silently nuke it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_request_metrics",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI request metric",
                "verbose_name_plural": "AI request metrics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="airm_tenant_ts_idx"),
                    models.Index(
                        fields=["tenant", "intent_classified"], name="airm_tenant_intent_idx"
                    ),
                    models.Index(fields=["tenant", "outcome"], name="airm_tenant_outcome_idx"),
                    models.Index(
                        fields=["tenant", "fallback_triggered"], name="airm_tenant_fallback_idx"
                    ),
                ],
            },
        ),
    ]
