# Generated by Django 5.2.14 on 2026-05-26 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0002_airequestmetric"),
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDailyMetricSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(
                        db_index=True,
                        help_text="UTC date the rollup covers. Beat schedules at 03:00 UTC and reads yesterday's `AIRequestMetric` rows (mirrors Sprint 8 cadence).",
                    ),
                ),
                (
                    "total_requests",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total AI requests handled this day. Drives all rate metrics.",
                    ),
                ),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("fallback_count", models.PositiveIntegerField(default=0)),
                ("escalated_count", models.PositiveIntegerField(default=0)),
                (
                    "latency_p50_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Median latency. NULL semantics: stored as 0 when total_requests==0.",
                    ),
                ),
                (
                    "latency_p95_ms",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="95th percentile latency in ms. Drives the < 3000ms threshold.",
                    ),
                ),
                ("latency_p99_ms", models.PositiveIntegerField(default=0)),
                ("total_tokens_input", models.PositiveBigIntegerField(default=0)),
                ("total_tokens_output", models.PositiveBigIntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Sum of `llm_cost_usd` across the day. Drives mean_cost_usd.",
                        max_digits=12,
                    ),
                ),
                (
                    "mean_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="`total_cost_usd / total_requests`. Drives the < $0.01 threshold.",
                        max_digits=12,
                    ),
                ),
                (
                    "task_success_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="`(AIRequestMetric.success_correlated_at IS NOT NULL count) / total_requests`. Drives the ≥ 0.80 threshold. Heuristic correlation via Conversation.last_booking_at within 60min of AI message.",
                    ),
                ),
                (
                    "fallback_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="`fallback_count / total_requests`. Drives the < 0.20 threshold.",
                    ),
                ),
                (
                    "intent_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="`{intent_label: count}` for the day. Dashboard surfaces the top-5 intents per tenant. Empty when total_requests==0.",
                    ),
                ),
                (
                    "threshold_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-metric verdict — `{metric: {value, threshold, op, status}}`. `status` in `ok`/`breach`/`no_data`. Empty when total_requests==0 (status becomes `{no_data: true}`). Dashboard reads this directly.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the aggregation task wrote this row."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the aggregation task last refreshed this row. Idempotent re-runs bump this without changing the payload.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — billing-adjacent rollup history.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_daily_metric_summaries",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI daily metric summary",
                "verbose_name_plural": "AI daily metric summaries",
                "ordering": ["-snapshot_date", "tenant"],
                "indexes": [
                    models.Index(fields=["tenant", "-snapshot_date"], name="aidm_tenant_date_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "snapshot_date"),
                        name="ai_daily_metric_one_per_tenant_per_day",
                    )
                ],
            },
        ),
    ]
