# Generated by Django 5.2.14 on 2026-05-27 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0013_rename_conv_aidraft_tnt_mst_stat_idx_conversatio_tenant__776ff2_idx_and_more",
        ),
        ("observability", "0003_aidailymetricsummary"),
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidailymetricsummary",
            name="abandoned_topic_count",
            field=models.IntegerField(
                default=0,
                help_text="Count of abandoned_topic signals — conversations idle >24h after AI message без booking. Trend down = AI engagement up.",
            ),
        ),
        migrations.AddField(
            model_name="aidailymetricsummary",
            name="cancelled_after_suggestion_count",
            field=models.IntegerField(
                default=0,
                help_text="Count of cancellation_after_suggestion signals — bookings created after AI recommendation but cancelled within 24h. Trend down = AI quality up.",
            ),
        ),
        migrations.AddField(
            model_name="aidailymetricsummary",
            name="repeat_interaction_count",
            field=models.IntegerField(
                default=0,
                help_text="Count of repeat_interaction signals — same skill invoked N+1 within session. Trend up = positive engagement.",
            ),
        ),
        migrations.CreateModel(
            name="ImplicitFeedbackSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            (
                                "cancellation_after_suggestion",
                                "Booking created → cancelled within 24h after AI suggestion",
                            ),
                            (
                                "abandoned_topic",
                                "Conversation idle >24h after AI message, no booking",
                            ),
                            ("repeat_interaction", "Same skill invoked N+1 within session"),
                            (
                                "completed_booking_reused",
                                "Mirror of W4 success_correlated_at — reserved, not written",
                            ),
                        ],
                        db_index=True,
                        help_text="Behavioral signal kind. Drives aggregation buckets on :class:`AIDailyMetricSummary`.",
                        max_length=48,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Signal-specific metadata (e.g. cancellation booking event id, idle duration ms, repeat count). MUST NOT contain raw user text per ADR-0011 §9 (analytics ≠ PII).",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When the daily aggregator detected this signal. Drives «signals detected last 7 days» dashboard query.",
                    ),
                ),
                (
                    "ai_request_metric",
                    models.ForeignKey(
                        help_text="Source AIRequestMetric row that triggered this signal (e.g. the AI recommendation that was later abandoned). CASCADE: if the source metric is purged (rare — metrics are forensic), the signal goes too — orphan signals have no audit context.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implicit_signals",
                        to="observability.airequestmetric",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning conversation. SET_NULL — same rationale as AIRequestMetric.conversation: 152-ФЗ forget-flow may purge the Conversation; the signal survives for analytics.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implicit_feedback_signals",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — signal history is forensic + analytics-adjacent; dropping a tenant must not silently nuke it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="implicit_feedback_signals",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Implicit feedback signal",
                "verbose_name_plural": "Implicit feedback signals",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["tenant", "-recorded_at"], name="ifs_tenant_ts_idx"),
                    models.Index(fields=["tenant", "signal_type"], name="ifs_tenant_type_idx"),
                    models.Index(
                        fields=["ai_request_metric", "signal_type"], name="ifs_metric_type_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_request_metric", "signal_type"), name="ifs_metric_type_unique"
                    )
                ],
            },
        ),
    ]
