# Generated by Django 5.2.14 on 2026-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0004_aidailymetricsummary_abandoned_topic_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestmetric",
            name="llm_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vendor-resolved model id for this LLM call (e.g. 'gpt-4o-mini', 'claude-haiku-4-5'). Empty when no LLM call or the writer predates DRF-1211 (pipeline / shadow paths). Needed to attribute cost to a model when SKILL_LLM_PROVIDER reroutes a skill.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="airequestmetric",
            name="llm_pass_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="1-based index of the LLM call within one user turn (multi-pass concierge, DRF-1266: 1 = first call, 2+ = follow-up passes fed with the tool result). NULL for single-pass writers (pipeline, shadow) — separates the cost of multi-pass from general traffic growth.",
                null=True,
            ),
        ),
    ]
