# Generated by Django 5.2.14 on 2026-09-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0024_drf1649_ayla_user_id_is_proxy"),
        ("observability", "0005_airequestmetric_llm_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequestmetric",
            name="bot_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user whose message triggered the AI request. SET_NULL on BotUser delete (owner §16.1): the metric survives, the subject does not. Nullable for system-triggered AI calls (proactive nudges, scheduled retention messages).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_request_metrics",
                to="identity.botuser",
            ),
        ),
    ]
