# Generated by Django 5.2.17 on 2026-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observability", "0006_airequestmetric_bot_user_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestmetric",
            name="llm_fallback_from",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DRF-2147 — provider slug the router asked FIRST and hopped away from (quota or unavailability) when llm_provider answered instead. Empty on a direct answer and when no LLM call. Lets ops count turns served by the fallback vendor and see which primary was down.",
                max_length=32,
            ),
        ),
    ]
