# Generated by Django 5.2.14 on 2026-05-17 04:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0005_tenant_manager_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Promo code shown to the customer. Stored UPPER-cased at save time so matching is case-insensitive without a Postgres-specific functional index.",
                        max_length=64,
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        help_text="Percent off the service base price. 1..99 — a 0% promo is a UI bug; a 100% promo would be a free service, handled through ops/handoff not the bot.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest moment the code is honourable. Null = no lower bound.",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Latest moment the code is honourable. Null = open-ended (until admin disables it).",
                        null=True,
                    ),
                ),
                (
                    "applicable_service_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of CatalogService.id UUIDs (as strings) the promo applies to. Empty = applies to ALL services on the tenant. Stored as JSON for cross-DB portability (see module docstring on the ArrayField vs JSONField call).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Admin kill-switch. False → validator returns ``inactive`` regardless of validity window. Preserves the row for audit + analytics ('how many tried to use this expired code last month?') instead of hard-deleting.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal-only operator notes (campaign source, approval link, etc.). Never shown to the customer.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — promo codes are operator-configured commercial settings; deleting a tenant requires explicit data purge first (audit + finance retention).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "code", "is_active"],
                        name="promotions__tenant__1a36e9_idx",
                    )
                ],
                "unique_together": {("tenant", "code")},
            },
        ),
    ]
