# Generated by Django 5.2.14 on 2026-05-20 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0004_master_invite_session"),
        ("identity", "0004_userpreferences"),
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterAdminThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("earnings_dispute", "Earnings dispute"),
                            ("leave_request", "Leave / schedule"),
                            ("review_concern", "Review concern"),
                            ("schedule_change", "Schedule change"),
                            ("offboarding_discussion", "Offboarding"),
                            ("other_master_complaint", "Other-master complaint"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        help_text="Topic per handoff §5.1. Re-tag is an admin power (handoff §4.4) — service layer enforces audit on change.",
                        max_length=32,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-generated from topic + first message OR admin-edited. Free-form short string — the UI uses this for list rendering when present, otherwise falls back to topic display.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open — awaiting first response"),
                            ("admin_responded", "Admin responded — awaiting master"),
                            ("master_responded", "Master responded — awaiting admin"),
                            ("active_discussion", "Active discussion"),
                            ("resolved", "Resolved"),
                            ("auto_closed_inactive", "Auto-closed (14d no activity)"),
                            ("escalated_to_founder", "Escalated to founder"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Lifecycle state. Transitions are enforced by the service layer; admins can PATCH directly for manual override.",
                        max_length=32,
                    ),
                ),
                (
                    "linked_artifact_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Polymorphic placeholder for the five typed FKs in handoff §6.1 — values like 'earning_dispute', 'leave_request'. Vocabulary controlled at the application layer; future PRs replace this with typed FKs as the target apps land.",
                        max_length=32,
                    ),
                ),
                (
                    "linked_artifact_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Opaque UUID of the linked artifact. NULL when ``linked_artifact_type`` is empty. No FK constraint by design — see module docstring.",
                        null=True,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Auto-True for OTHER_MASTER_COMPLAINT and OFFBOARDING_DISCUSSION topics per handoff §5.4. Receptionists see the row in their queue but cannot view the message body unless they're the ``assigned_admin``.",
                    ),
                ),
                (
                    "founder_added_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the master escalated to founder per handoff §3.6. NULL when no escalation; non-NULL pairs with status=ESCALATED_TO_FOUNDER.",
                        null=True,
                    ),
                ),
                (
                    "sla_due_at",
                    models.DateTimeField(
                        help_text="First-response SLA deadline. Computed at create time from topic per handoff §5.1; never updated on re-tag."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated on every save. The service layer also explicitly stamps it on send_message so the list ordering stays correct even when other fields didn't change.",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Future PR: 90d-inactive auto-archive per handoff §2.8.",
                        null=True,
                    ),
                ),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional pinning per handoff §4.3. SET_NULL on BotUser delete so the thread survives the admin leaving.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.botuser",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        help_text="The master who opened the thread. CASCADE — deleting a master also drops their internal-chat history (the audit row trail remains independently via apps.audit).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_threads",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — a tenant delete drops every thread along with the tenant's master/staff data.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_admin_threads",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master-admin thread",
                "verbose_name_plural": "Master-admin threads",
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterAdminMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("master", "Master"),
                            ("admin", "Admin / Owner / Receptionist"),
                            ("founder", "Founder"),
                            ("system", "System (auto-close, etc.)"),
                        ],
                        help_text="Role chip per handoff §2.7. Receptionists send as role='admin' too — masters see «Студия» regardless of which specific admin replied unless the admin explicitly signs.",
                        max_length=16,
                    ),
                ),
                (
                    "sender_admin_signed_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional «— Натали» signature per handoff §2.7 / §6.2. Empty for the default «Студия» sender identity.",
                        max_length=64,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Plain-text message body. Customer PII filter (handoff §8.1) lands in a future PR; PR 6 trusts the master/admin to follow the policy.",
                        max_length=4000,
                    ),
                ),
                ("read_by_master_at", models.DateTimeField(blank=True, null=True)),
                ("read_by_admin_at", models.DateTimeField(blank=True, null=True)),
                ("read_by_founder_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False,
                        help_text="True for auto-close / auto-archive / 'thread escalated' notices. Renders differently in the UI (italic, no sender chrome).",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for SYSTEM messages (auto-close, auto-archive). SET_NULL on BotUser delete so the message history survives.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="identity.botuser",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="Owning thread. CASCADE — deleting a thread drops every message + attachment (cascade-cascade).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="internal_chat.masteradminthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master-admin message",
                "verbose_name_plural": "Master-admin messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MasterAdminMessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("image", "Image (JPEG/PNG/WebP)"),
                            ("pdf", "PDF"),
                            ("voice_memo", "Voice memo"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Storage path is filesystem today (FileField). S3 migration is a future PR.",
                        upload_to="master_admin_chat/",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.IntegerField(
                        help_text="Stored separately from the FileField's size attribute so audit trails survive a storage-tier migration."
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        help_text="Hex SHA-256 of the file bytes. Used for dedup + tamper detection in the future PII scan pipeline.",
                        max_length=64,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Voice-memo length in seconds. NULL for image/PDF.",
                        null=True,
                    ),
                ),
                (
                    "pii_scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting scan"),
                            ("clean", "Clean"),
                            ("flagged", "Flagged — review"),
                            ("blocked", "Blocked — customer PII detected"),
                        ],
                        default="pending",
                        help_text="Customer-photo filter status per handoff §3.7. Pipeline deferred to a future PR — every row stays PENDING in PR 6.",
                        max_length=32,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Owning message. CASCADE — deleting a message drops its attachments along with it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="internal_chat.masteradminmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master-admin message attachment",
                "verbose_name_plural": "Master-admin message attachments",
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(fields=["message"], name="internal_ch_message_7bb2e4_idx"),
                    models.Index(
                        fields=["pii_scan_status", "uploaded_at"],
                        name="internal_ch_pii_sca_ddd850_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="masteradminthread",
            index=models.Index(
                fields=["tenant", "status", "-last_activity_at"],
                name="internal_ch_tenant__a506a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="masteradminthread",
            index=models.Index(
                fields=["master", "-last_activity_at"], name="internal_ch_master__bce53e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masteradminthread",
            index=models.Index(fields=["sla_due_at"], name="internal_ch_sla_due_a2a6f5_idx"),
        ),
        migrations.AddIndex(
            model_name="masteradminthread",
            index=models.Index(
                fields=["linked_artifact_type", "linked_artifact_id"],
                name="internal_ch_linked__06e875_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="masteradminthread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("topic__in", ["other_master_complaint", "offboarding_discussion"]),
                        _negated=True,
                    ),
                    ("is_sensitive", True),
                    _connector="OR",
                ),
                name="ck_internal_chat_sensitive_topics_flagged",
            ),
        ),
        migrations.AddIndex(
            model_name="masteradminmessage",
            index=models.Index(
                fields=["thread", "-sent_at"], name="internal_ch_thread__395ed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masteradminmessage",
            index=models.Index(
                fields=["thread", "read_by_master_at"], name="internal_ch_thread__509d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="masteradminmessage",
            index=models.Index(
                fields=["thread", "read_by_admin_at"], name="internal_ch_thread__b007e7_idx"
            ),
        ),
    ]
