# Generated by Django 5.2.14 on 2026-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_catalogmaster_cache_version"),
        ("identity", "0014_seed_global_bot_tenant"),
        ("internal_chat", "0001_initial"),
        ("tenancy", "0010_tenant_city"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="masteradminthread",
            name="ck_internal_chat_sensitive_topics_flagged",
        ),
        migrations.AddConstraint(
            model_name="masteradminthread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "topic__in",
                            ["offboarding_discussion", "other_master_complaint"],
                        ),
                        _negated=True,
                    ),
                    ("is_sensitive", True),
                    _connector="OR",
                ),
                name="ck_internal_chat_sensitive_topics_flagged",
            ),
        ),
    ]
