# Generated by Django 5.2.5 on 2026-05-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0008_tenant_cost_caps"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        help_text="ULID per taxonomy §2. Time-sortable; outbox FIFO relies on it.",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        help_text="dot.notation canonical name from taxonomy §3 catalog.",
                        max_length=120,
                    ),
                ),
                (
                    "event_version",
                    models.CharField(
                        default="1.0",
                        help_text="SemVer per taxonomy §7. Bump on payload-shape change.",
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="UTC. Producer-supplied (NOT auto_now) so replay can reconstruct the original moment."
                    ),
                ),
                (
                    "actor",
                    models.JSONField(
                        default=dict,
                        help_text="{type, id, role} per taxonomy §2. type is always set.",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ULID per Q-EV-IMPL5. Empty when not part of a chain.",
                        max_length=64,
                    ),
                ),
                (
                    "causation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ULID of the event that caused this one. Empty otherwise.",
                        max_length=26,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Per-event payload. NEVER raw PII — taxonomy §6 enforced at emit time; violations REJECT the row.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Implementation tags (replay flag, environment, etc.). Same PII rules as data.",
                    ),
                ),
                (
                    "is_dispatched",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="False until the dispatcher hands the envelope to subscribers.",
                    ),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the dispatcher marks the row complete.",
                        null=True,
                    ),
                ),
                (
                    "dispatch_attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Increment on each failed dispatch attempt. Dead-letter threshold per taxonomy §5 is checked by the dispatcher.",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Most recent dispatcher error message. Truncated by caller.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="DB insertion time. Distinct from occurred_at — the former is monotonic by definition, the latter is producer time.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owning tenant. Null for system.* events (taxonomy §8).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_events",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain event",
                "verbose_name_plural": "Domain events",
                "ordering": ["event_id"],
                "indexes": [
                    models.Index(
                        fields=["is_dispatched", "event_id"], name="evbus_outbox_pending_idx"
                    ),
                    models.Index(
                        fields=["tenant", "event_name", "-occurred_at"],
                        name="evbus_tenant_name_idx",
                    ),
                    models.Index(fields=["correlation_id"], name="evbus_correlation_idx"),
                ],
            },
        ),
    ]
