# Generated by Django 5.2.5 on 2026-05-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainevent",
            name="dead_lettered_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set by dispatcher when dispatch_attempts crosses MAX_ATTEMPTS. Dead-letter rows are excluded from re-claim; ops triage + replay action in admin restarts them. Phase 2.2 — replaces Phase 2.1 forever-pending workaround (taxonomy §18.5).",
                null=True,
            ),
        ),
    ]
