# Generated by Django 5.2.5 on 2026-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0002_domainevent_dead_lettered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestDedupe",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        help_text="ULID from the cross-service envelope §2.event_id. PK so concurrent inserts hit a uniqueness constraint rather than racing in application code.",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_name", models.CharField(max_length=120)),
                ("event_version", models.IntegerField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        help_text="Set to ``now()`` in the same transaction as the consumer's side-effect."
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingest dedupe row",
                "verbose_name_plural": "Ingest dedupe ledger",
                "indexes": [
                    models.Index(fields=["received_at"], name="evbus_ingest_dedupe_recv_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="IngestDLQ",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="ULID from envelope §2.event_id. Indexed for replay lookups.",
                        max_length=26,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=120)),
                ("event_version", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        help_text="Slug from `event-contract.md` §8 (e.g. ``unknown_event_name``, ``unknown_event_version``, ``handler_exception``, ``retry_budget_exhausted``).",
                        max_length=64,
                    ),
                ),
                (
                    "raw_body",
                    models.JSONField(
                        help_text="Full envelope payload at receipt. PII rules §7 already limit what may appear here, but operators MUST treat this table as 152-ФЗ-sensitive nonetheless."
                    ),
                ),
                ("dead_lettered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replayed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when an operator manually re-publishes the entry. Distinct from received-during-replay; the latter goes through the normal dedupe ledger above.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingest DLQ entry",
                "verbose_name_plural": "Ingest DLQ entries",
                "indexes": [
                    models.Index(fields=["-dead_lettered_at"], name="evbus_dlq_recent_idx"),
                    models.Index(fields=["reason"], name="evbus_dlq_reason_idx"),
                ],
            },
        ),
    ]
