# Generated by Django 5.2.5 on 2026-05-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0003_ingest_dedupe_dlq"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerminalDedupe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        help_text="Tenant scoping the dedupe row. Round-2 NEW-1: without this, a malicious tenant could pre-claim a victim's (payment_id, terminal_state) globally and block the victim's legitimate loyalty fan-out forever — category-2 cross-tenant DoS. UUIDField (not FK) — this is a system-level dedupe ledger; we keep CASCADE semantics out of the picture and rely on retention sweeps for cleanup."
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(help_text="Canonical Ayla Payment.id from the event payload."),
                ),
                (
                    "terminal_state",
                    models.CharField(
                        choices=[("captured", "Captured"), ("refunded", "Refunded")],
                        help_text="Which terminal state we've already processed for this payment_id. A row's existence is the dedupe signal.",
                        max_length=16,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="ULID of the event that first reached this terminal state. Forensic trace — distinct events with the same (tenant_id, payment_id, terminal_state) tuple after this row exists are no-op'd at the handler layer.",
                        max_length=26,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Payment terminal dedupe row",
                "verbose_name_plural": "Payment terminal dedupe ledger",
                "indexes": [
                    models.Index(fields=["processed_at"], name="evbus_payment_term_proc_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "payment_id", "terminal_state"),
                        name="evbus_payment_terminal_unique",
                    )
                ],
            },
        ),
    ]
