# Generated by Django 5.2.5 on 2026-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0004_payment_terminal_dedupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewProcessedDedupe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        help_text="Tenant scoping the dedupe row. Mirrors the PaymentTerminalDedupe.tenant_id pattern (#443 Round-2 NEW-1) so a malicious tenant cannot pre-claim a victim's review_id."
                    ),
                ),
                (
                    "review_id",
                    models.UUIDField(help_text="Canonical Ayla Review.id from the event payload."),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="ULID of the event that first processed this review. Forensic trace — distinct events with the same (tenant_id, review_id) after this row exists are no-op'd.",
                        max_length=26,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Review processed dedupe row",
                "verbose_name_plural": "Review processed dedupe ledger",
                "indexes": [
                    models.Index(fields=["processed_at"], name="evbus_review_proc_proc_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "review_id"), name="evbus_review_processed_unique"
                    )
                ],
            },
        ),
    ]
