# Generated by Django 5.2.5 on 2026-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0005_review_processed_dedupe"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandlerFailureTracker",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_id",
                    models.CharField(help_text="ULID from envelope §2.event_id.", max_length=26),
                ),
                (
                    "handler_name",
                    models.CharField(
                        help_text="``{event_name}@v{event_version}`` — the registered handler whose invocation raised. Distinct handlers for the same event_id (theoretical multi-handler future) keep independent counters.",
                        max_length=140,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        default="handler_exception",
                        help_text="Future-proof for richer outcomes (timeout, permanent_failure). MVP only writes ``handler_exception``.",
                        max_length=32,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of failed dispatch attempts for this (event_id, handler, outcome) triple. Incremented on every HANDLER_EXCEPTION; reset only by operator action.",
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Truncated ``exc_type: str(exc)`` from the most recent failure. Stack traces live in the log aggregator.",
                        max_length=1024,
                    ),
                ),
                ("first_attempt_at", models.DateTimeField(auto_now_add=True)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Handler failure tracker",
                "verbose_name_plural": "Handler failure tracker",
            },
        ),
        migrations.AddConstraint(
            model_name="ingestdlq",
            constraint=models.UniqueConstraint(
                fields=("event_id", "reason"), name="evbus_dlq_event_reason_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="handlerfailuretracker",
            index=models.Index(fields=["-last_attempt_at"], name="evbus_handler_fail_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="handlerfailuretracker",
            index=models.Index(fields=["handler_name"], name="evbus_handler_fail_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="handlerfailuretracker",
            constraint=models.UniqueConstraint(
                fields=("event_id", "handler_name", "outcome"), name="evbus_handler_failure_unique"
            ),
        ),
    ]
