# Generated by Django 5.2.5 on 2026-05-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0006_handler_failure_tracker_and_dlq_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestdlq",
            name="dead_lettered_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Time the row was first dead-lettered. ``auto_now_add`` (NOT ``auto_now``) is intentional: with the #433 upsert pattern, subsequent failures past threshold REFRESH the row via ``update_or_create`` but MUST NOT overwrite this timestamp. Operator triage cares about «when did this event first fail», not «when was the most recent retry». The most-recent-retry signal lives on HandlerFailureTracker.last_attempt_at.",
            ),
        ),
    ]
