# Generated by Django 5.2.14 on 2026-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0007_ingestdlq_dead_lettered_at_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDispatchDedupe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tenant_id",
                    models.UUIDField(
                        help_text="Tenant scoping the dedupe row — blocks cross-tenant pre-claim suppression of a victim's notification. UUIDField (not FK): system-level ledger, cleaned by retention sweeps."
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="ULID of the cross-service event that triggered the notification. Part of the exactly-once key.",
                        max_length=26,
                    ),
                ),
                (
                    "recipient_id",
                    models.UUIDField(
                        help_text="Canonical Ayla User.id the notification is sent to."
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="Delivery channel (e.g. ``max``). A given event may legitimately notify the same user on different channels.",
                        max_length=32,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="Notification kind (e.g. ``payment_failed``). Forensic label — NOT part of the unique key (one event → one notification per channel regardless of kind).",
                        max_length=64,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification dispatch dedupe row",
                "verbose_name_plural": "Notification dispatch dedupe ledger",
                "indexes": [models.Index(fields=["dispatched_at"], name="evbus_notif_disp_at_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "event_id", "recipient_id", "channel"),
                        name="evbus_notif_dispatch_unique",
                    )
                ],
            },
        ),
    ]
