# Generated by Django 5.2.14 on 2026-07-03 03:01
#
# #1058 — widen every cross-service ingest event_id column from
# varchar(26) (ULID width) to varchar(36) so Ayla's uuid4() (36 chars)
# fits. The contract (event-contract.md §2) documents a bare ULID, but
# the outbox emits uuid4 in practice; a 36-char id currently raises
# Postgres DataError on the INSERT → HANDLER_EXCEPTION → 500 → Ayla
# retries a permanently-broken event forever.
#
# Columns widened (all in apps/eventbus/models.py):
#   IngestDedupe.event_id (PK)      — the universal dedupe gate
#   IngestDLQ.event_id (indexed)    — dead-letter forensic key
#   HandlerFailureTracker.event_id  — retry counter
#   PaymentTerminalDedupe.event_id  — captured/refunded 2nd-layer guard
#   ReviewProcessedDedupe.event_id  — review.created 2nd-layer guard
#   NotificationDispatchDedupe.event_id — payment.failed DM exactly-once
#
# NOT covered here (cross-app, other streams — see #1058 follow-up):
#   RemoteBookingProxy.last_synced_event_id (apps/booking, varchar 26)
#   Conversation.last_payment_event_id (apps/conversations, varchar 26)
# Until those two are widened, a real 36-char booking.*/payment.* event
# will pass dedupe here but still DataError inside its consumer. This
# migration fixes every event_id column THIS stream owns; the remaining
# two require a coordinated cross-stream migration before pilot.
#
# Migration safety: all operations only INCREASE a varchar length limit.
# Postgres does NOT rewrite the table or reindex for a varchar length
# increase (it updates atttypmod in the catalog under a brief — sub-ms —
# ACCESS EXCLUSIVE lock; it momentarily blocks concurrent ingest but does
# not scan rows). No data is lost; existing 26-char rows are untouched;
# the IngestDedupe PK unique index and the unique constraints on the
# dedupe tables remain valid (values are unchanged, binary-coercible).
# Reverse (36→26) is forward-safe: Postgres ABORTS the reverse ALTER
# loudly with "value too long" if any >26-char row exists — it never
# silently truncates.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventbus", "0008_notificationdispatchdedupe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handlerfailuretracker",
            name="event_id",
            field=models.CharField(
                help_text="Cross-service envelope §2.event_id (bare ULID 26 chars or Ayla uuid4 36 chars, #1058).",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="ingestdedupe",
            name="event_id",
            field=models.CharField(
                help_text="Cross-service envelope §2.event_id. varchar(36) holds both a bare ULID (26 chars) and Ayla's uuid4() (36 chars) — the spec says ULID but the outbox emits uuid4 in practice (#1058). PK so concurrent inserts hit a uniqueness constraint rather than racing in application code.",
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ingestdlq",
            name="event_id",
            field=models.CharField(
                db_index=True,
                help_text="Cross-service envelope §2.event_id (bare ULID 26 chars or Ayla uuid4 36 chars, #1058). Indexed for replay lookups. Over-length ids are rejected fail-fast before reaching this table (see ingest_dispatcher event_id_too_long guard); the DLQ writer truncates defensively so a contract-violating id cannot turn the DLQ write itself into a DataError.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="notificationdispatchdedupe",
            name="event_id",
            field=models.CharField(
                help_text="Cross-service event_id (ULID 26 or Ayla uuid4 36, #1058) of the event that triggered the notification. Part of the exactly-once key.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="paymentterminaldedupe",
            name="event_id",
            field=models.CharField(
                help_text="Cross-service event_id (ULID 26 or Ayla uuid4 36, #1058) of the event that first reached this terminal state. Forensic trace — distinct events with the same (tenant_id, payment_id, terminal_state) tuple after this row exists are no-op'd at the handler layer.",
                max_length=36,
            ),
        ),
        migrations.AlterField(
            model_name="reviewprocesseddedupe",
            name="event_id",
            field=models.CharField(
                help_text="Cross-service event_id (ULID 26 or Ayla uuid4 36, #1058) of the event that first processed this review. Forensic trace — distinct events with the same (tenant_id, review_id) after this row exists are no-op'd.",
                max_length=36,
            ),
        ),
    ]
