# Generated by Django 5.2.14 on 2026-05-12 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        help_text="Pipeline trace id (uuid7 stringified). Propagated via ``apps.tenancy.context::current_trace_id`` ContextVar. Unique within tenant by convention; not DB-enforced because trace_id origin is the pipeline layer.",
                        max_length=64,
                    ),
                ),
                (
                    "pipeline_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of step snapshots: input message, intent decision, safety verdict, retrieved passages (IDs + scores only — NEVER raw content), tool calls + results, draft text, final text. PII-redacted before persist by ``apps.replay.redactor``.",
                    ),
                ),
                (
                    "redacted",
                    models.BooleanField(
                        default=True,
                        help_text="True iff `pipeline_steps` passed through the redactor. Phase 0 always True — recorder always redacts. Field exists to support a future raw-trace mode for testing (never prod).",
                    ),
                ),
                (
                    "redaction_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Identifier of the redactor version that processed this row (e.g. "regex_v1"). Lets a future migration re-redact rows captured under an older method without raw-text access.',
                        max_length=32,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Hard-delete deadline. Stamped by the recorder at capture time as ``captured_at + REPLAY_RETENTION_DAYS``. The daily Celery cleanup task evicts past-expiry rows (Sprint 5 / A4)."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — replay data is forensic; accidental tenant delete must not vapourise it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replay_traces",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replay trace",
                "verbose_name_plural": "Replay traces",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-captured_at"], name="replay_repl_tenant__34479a_idx"
                    ),
                    models.Index(fields=["trace_id"], name="replay_repl_trace_i_dbb4c9_idx"),
                    models.Index(fields=["expires_at"], name="replay_repl_expires_cd6c79_idx"),
                ],
            },
        ),
    ]
