# Generated by Django 5.2.14 on 2026-05-11 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("personal_data", "Personal data (152-ФЗ)"),
                            ("marketing", "Marketing"),
                            ("photo_biometric", "Photo / biometric"),
                            ("health", "Health"),
                        ],
                        help_text="Which consent this row is about. See ConsentType for the 4 Phase-0 categories.",
                        max_length=32,
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=False,
                        help_text="True when the user actively granted. False rows exist for explicit-decline audit (user said 'no' to MARKETING).",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text='Where the consent came from. Free-form but conventional: "bot_message:<msg-uuid>" (explicit /command), "admin:override" (operator), "registration_form" (wizard), "implicit_first_msg" (152-ФЗ baseline auto-grant).',
                        max_length=64,
                    ),
                ),
                (
                    "document_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Snapshot of which privacy-policy version the user saw. Empty for legacy / implicit grants. Example: "privacy-v1.2".',
                        max_length=32,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by withdraw(); leaves the row in DB as audit trail.",
                        null=True,
                    ),
                ),
                (
                    "bot_user",
                    models.ForeignKey(
                        help_text="The user this consent belongs to. CASCADE because ConsentRecord is forensic-supporting metadata for the user; when the user is fully deleted via `delete_bot_user_data` (Sprint 2.5 H1), their consent history goes with them. The audit trail of the deletion itself lives in AuditLog.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalised for the E1 leakage scanner + per-tenant consent queries (Sprint 5+ replay). Mirrors bot_user.tenant.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent record",
                "verbose_name_plural": "Consent records",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["bot_user", "consent_type", "-captured_at"],
                        name="consent_con_bot_use_e3753d_idx",
                    ),
                    models.Index(
                        fields=["tenant", "consent_type", "granted"],
                        name="consent_con_tenant__c1beaa_idx",
                    ),
                ],
            },
        ),
    ]
