# Generated by Django 5.2.14 on 2026-09-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0003_backfill_memory_green_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentrecord",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("personal_data", "Personal data (152-ФЗ)"),
                    ("marketing", "Marketing"),
                    ("photo_biometric", "Photo / biometric"),
                    ("health", "Health"),
                    ("memory_green", "Memory — green zone"),
                    ("memory_yellow", "Memory — yellow zone"),
                    ("memory_red", "Memory — red zone (special category)"),
                    (
                        "nutrition_diary",
                        "Nutrition diary (food, drinks, photos, voice)",
                    ),
                    (
                        "personal_calculation",
                        "Personal calculation (weight, height, age, sex, activity, goal)",
                    ),
                ],
                help_text="Which consent this row is about. See ConsentType for the 4 Phase-0 categories.",
                max_length=32,
            ),
        ),
    ]
