# Generated by Django 5.2.17 on 2026-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0006_backfill_tenant_welcome_personal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentrecord",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("personal_data", "Personal data (152-ФЗ)"),
                    ("marketing", "Marketing"),
                    ("photo_biometric", "Photo / biometric"),
                    ("health", "Health"),
                    ("memory_green", "Memory — green zone"),
                    ("memory_yellow", "Memory — yellow zone"),
                    ("memory_red", "Memory — red zone (special category)"),
                    (
                        "food_diary_processing",
                        "Food diary processing (food, drinks, photos, voice)",
                    ),
                    (
                        "personal_calculation",
                        "Personal calculation (weight, height, age, sex, activity, goal)",
                    ),
                    (
                        "preference_inference",
                        "Preference inference (Ayla proposes preferences to remember)",
                    ),
                ],
                help_text="Which consent this row is about. See ConsentType for the 4 Phase-0 categories.",
                max_length=32,
            ),
        ),
    ]
