# Generated by Django 5.2.14 on 2026-05-18 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0007_tenant_telegram_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slot_granularity_min",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Grid step in minutes for candidate slot starts. Default 15. Range 5–60.",
                    ),
                ),
                (
                    "buffer_min",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Minimum gap (minutes) before AND after every occupied interval. Lets the master prep / clean the station. Default 5. Range 0–60.",
                    ),
                ),
                (
                    "lead_time_min",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Minimum minutes between now and the earliest bookable start. Default 60. Range 0–2880 (48h).",
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Don't surface slots farther than this many days ahead. Default 60. Range 7–180.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_config",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slot config",
                "verbose_name_plural": "Slot configs",
            },
        ),
        migrations.CreateModel(
            name="ScheduleChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "requested_change",
                    models.JSONField(
                        default=dict,
                        help_text="Diff structure — writer-defined shape. Common keys: type (working_hours_change / exception_add), day_of_week, new_start, new_end, date, exception_type, reason.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Master's free-form rationale (e.g. «утренние йога»).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled by master"),
                            ("auto_escalated", "Auto-escalated (72h timeout)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True, default="", help_text="Owner's note on approval/rejection."
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master",
                    models.ForeignKey(
                        help_text="Master who submitted the request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_change_requests",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_change_requests",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule change request",
                "verbose_name_plural": "Schedule change requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="scheduling__tenant__62cbd5_idx",
                    ),
                    models.Index(
                        fields=["tenant", "master", "-created_at"],
                        name="scheduling__tenant__d137df_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(help_text="Calendar date in tenant-local timezone.")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vacation", "Отпуск"),
                            ("sick_leave", "Больничный"),
                            ("day_off", "Выходной"),
                            ("custom_hours", "Изменён график"),
                            ("event", "Корпоратив / обучение"),
                        ],
                        help_text="5-value enum per schedule-management handoff §1.",
                        max_length=16,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Required for type=custom_hours, must be NULL for all other types.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Required for type=custom_hours, must be NULL for all other types.",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form note visible to the salon team only.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule exception",
                "verbose_name_plural": "Schedule exceptions",
                "ordering": ["-date", "master_id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "master", "date"], name="scheduling__tenant__55a842_idx"
                    ),
                    models.Index(
                        fields=["tenant", "type", "date"], name="scheduling__tenant__4f7a8a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master", "date"), name="schedule_exception_one_per_master_date"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", False),
                                ("start_time__isnull", False),
                                ("type", "custom_hours"),
                            ),
                            models.Q(
                                models.Q(("type", "custom_hours"), _negated=True),
                                ("end_time__isnull", True),
                                ("start_time__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="schedule_exception_times_match_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_time__isnull", True),
                            ("end_time__gt", models.F("start_time")),
                            _connector="OR",
                        ),
                        name="schedule_exception_end_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Block start instant (timezone-aware, stored UTC)."
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="Block end instant (timezone-aware, stored UTC). Exclusive — a candidate slot starting exactly at end_at is allowed."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Human-readable note for the salon team. Common: «обед», «уборка», «подготовка», «просто занято».",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time block",
                "verbose_name_plural": "Time blocks",
                "ordering": ["master_id", "start_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "master", "start_at"],
                        name="scheduling__tenant__ccd147_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="time_block_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "day_of_week",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="0=Monday … 6=Sunday — matches Python date.weekday().",
                    ),
                ),
                (
                    "is_working",
                    models.BooleanField(
                        default=True,
                        help_text="False = recurring weekly day off. When False, all time fields must be null.",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Block start in tenant-local TZ. Inclusive. Required when is_working=True.",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Block end in tenant-local TZ. Exclusive (last bookable start is end_time minus service duration). Required when is_working=True.",
                        null=True,
                    ),
                ),
                (
                    "lunch_start",
                    models.TimeField(
                        blank=True,
                        help_text="Optional recurring lunch start. The resolver splits the working block around lunch_start..lunch_end.",
                        null=True,
                    ),
                ),
                (
                    "lunch_end",
                    models.TimeField(
                        blank=True,
                        help_text="Optional recurring lunch end. Must be set together with lunch_start.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this row. Null for system / migration backfills.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Working hours",
                "verbose_name_plural": "Working hours",
                "ordering": ["master_id", "day_of_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master", "day_of_week"),
                        name="working_hours_one_row_per_master_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_time__isnull", True),
                                ("is_working", False),
                                ("start_time__isnull", True),
                            ),
                            models.Q(
                                ("end_time__isnull", False),
                                ("is_working", True),
                                ("start_time__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="working_hours_times_match_is_working",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_time__isnull", True),
                            ("end_time__gt", models.F("start_time")),
                            _connector="OR",
                        ),
                        name="working_hours_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("lunch_end__isnull", True), ("lunch_start__isnull", True)),
                            models.Q(("lunch_end__isnull", False), ("lunch_start__isnull", False)),
                            _connector="OR",
                        ),
                        name="working_hours_lunch_both_or_neither",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lunch_end__isnull", True),
                            ("lunch_end__gt", models.F("lunch_start")),
                            _connector="OR",
                        ),
                        name="working_hours_lunch_end_after_start",
                    ),
                ],
            },
        ),
    ]
