# Generated by Django 5.2.14 on 2026-05-21 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_catalogmaster_archive_reason"),
        ("identity", "0004_userpreferences"),
        ("scheduling", "0001_initial"),
        ("tenancy", "0009_tenantstaff"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulechangerequest",
            name="reason_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vacation", "Отпуск"),
                    ("sick", "Больничный"),
                    ("personal", "Личные дела"),
                    ("other", "Другое"),
                ],
                default="",
                help_text="Closed-set classification of the master's reason. Empty for legacy rows that pre-date the M3 typed endpoint.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="reason_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short free-form note from the master (≤200 chars). The longer ``reason`` text field stays as the legacy free-form fallback for callers that pre-date the M3 endpoint.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="BotUser who submitted via the M3 endpoint. NULL for system-generated or legacy rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.botuser",
            ),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="requested_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End of the proposed off-time window (UTC). Set by M3 POST /api/master/availability; null for legacy rows. Always > requested_start when both are set.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schedulechangerequest",
            name="requested_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the proposed off-time window (UTC). Set by M3 POST /api/master/availability; null for legacy requested_change-only rows.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulechangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_start__isnull", True),
                    ("requested_end__isnull", True),
                    ("requested_end__gt", models.F("requested_start")),
                    _connector="OR",
                ),
                name="schedule_change_request_end_after_start",
            ),
        ),
    ]
