# Generated by Django 5.2.14 on 2026-09-08 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_catalogfaq_options_and_more"),
        ("identity", "0022_botuser_blocked_at_botuser_blocked_by_username_and_more"),
        ("scheduling", "0003_schedulechangerequest_resolved_by_bot_user_id"),
        ("tenancy", "0015_tenant_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedulechangerequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Заявка на изменение расписания",
                "verbose_name_plural": "Заявки на изменение расписания",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleexception",
            options={
                "ordering": ["-date", "master_id"],
                "verbose_name": "Исключение в расписании",
                "verbose_name_plural": "Исключения в расписании",
            },
        ),
        migrations.AlterModelOptions(
            name="slotconfig",
            options={
                "verbose_name": "Настройка сетки записи",
                "verbose_name_plural": "Настройки сетки записи",
            },
        ),
        migrations.AlterModelOptions(
            name="timeblock",
            options={
                "ordering": ["master_id", "start_at"],
                "verbose_name": "Блокировка времени",
                "verbose_name_plural": "Блокировки времени",
            },
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "ordering": ["master_id", "day_of_week"],
                "verbose_name": "Рабочие часы мастера",
                "verbose_name_plural": "Рабочие часы мастеров",
            },
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="master",
            field=models.ForeignKey(
                help_text="Master who submitted the request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_change_requests",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Master's free-form rationale (e.g. «утренние йога»).",
                verbose_name="Причина",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="reason_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vacation", "Отпуск"),
                    ("sick", "Больничный"),
                    ("personal", "Личные дела"),
                    ("other", "Другое"),
                ],
                default="",
                help_text="Closed-set classification of the master's reason. Empty for legacy rows that pre-date the M3 typed endpoint.",
                max_length=16,
                verbose_name="Класс причины",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="reason_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short free-form note from the master (≤200 chars). The longer ``reason`` text field stays as the legacy free-form fallback for callers that pre-date the M3 endpoint.",
                max_length=200,
                verbose_name="Причина словами мастера",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="BotUser who submitted via the M3 endpoint. NULL for system-generated or legacy rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.botuser",
                verbose_name="Кто попросил",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="requested_change",
            field=models.JSONField(
                default=dict,
                help_text="Diff structure — writer-defined shape. Common keys: type (working_hours_change / exception_add), day_of_week, new_start, new_end, date, exception_type, reason.",
                verbose_name="Что просят изменить",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="requested_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End of the proposed off-time window (UTC). Set by M3 POST /api/master/availability; null for legacy rows. Always > requested_start when both are set.",
                null=True,
                verbose_name="Желаемое окончание",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="requested_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the proposed off-time window (UTC). Set by M3 POST /api/master/availability; null for legacy requested_change-only rows.",
                null=True,
                verbose_name="Желаемое начало",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="resolution_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Owner's note on approval/rejection.",
                verbose_name="Решение",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Решено"),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто решил",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="resolved_by_bot_user_id",
            field=models.UUIDField(
                blank=True,
                help_text="BotUser.id of the admin/owner who decided this request. Populated even when ``resolved_by`` FK is NULL.",
                null=True,
                verbose_name="Кто решил (аккаунт в мессенджере)",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled by master"),
                    ("auto_escalated", "Auto-escalated (72h timeout)"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Состояние заявки",
            ),
        ),
        migrations.AlterField(
            model_name="schedulechangerequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_change_requests",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем задано",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="date",
            field=models.DateField(
                help_text="Calendar date in tenant-local timezone.", verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Required for type=custom_hours, must be NULL for all other types.",
                null=True,
                verbose_name="Окончание",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_exceptions",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form note visible to the salon team only.",
                verbose_name="Причина",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Required for type=custom_hours, must be NULL for all other types.",
                null=True,
                verbose_name="Начало",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_exceptions",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="type",
            field=models.CharField(
                choices=[
                    ("vacation", "Отпуск"),
                    ("sick_leave", "Больничный"),
                    ("day_off", "Выходной"),
                    ("custom_hours", "Изменён график"),
                    ("event", "Корпоратив / обучение"),
                ],
                help_text="5-value enum per schedule-management handoff §1.",
                max_length=16,
                verbose_name="Вид исключения",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleexception",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="buffer_min",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Minimum gap (minutes) before AND after every occupied interval. Lets the master prep / clean the station. Default 5. Range 0–60.",
                verbose_name="Буфер между записями, мин",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="lead_time_min",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Minimum minutes between now and the earliest bookable start. Default 60. Range 0–2880 (48h).",
                verbose_name="Минимальный запас до визита, мин",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="max_advance_days",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Don't surface slots farther than this many days ahead. Default 60. Range 7–180.",
                verbose_name="На сколько дней вперёд можно записаться",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="slot_granularity_min",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Grid step in minutes for candidate slot starts. Default 15. Range 5–60.",
                verbose_name="Шаг сетки записи, мин",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_config",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="slotconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем задан",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="end_at",
            field=models.DateTimeField(
                help_text="Block end instant (timezone-aware, stored UTC). Exclusive — a candidate slot starting exactly at end_at is allowed.",
                verbose_name="Конец блокировки",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_blocks",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="reason",
            field=models.CharField(
                help_text="Human-readable note for the salon team. Common: «обед», «уборка», «подготовка», «просто занято».",
                max_length=200,
                verbose_name="Причина",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="start_at",
            field=models.DateTimeField(
                help_text="Block start instant (timezone-aware, stored UTC).",
                verbose_name="Начало блокировки",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_blocks",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who created this row. Null for system / migration backfills.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем задано",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="day_of_week",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                help_text="0=Monday … 6=Sunday — matches Python date.weekday().",
                verbose_name="День недели",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Block end in tenant-local TZ. Exclusive (last bookable start is end_time minus service duration). Required when is_working=True.",
                null=True,
                verbose_name="Конец смены",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="is_working",
            field=models.BooleanField(
                default=True,
                help_text="False = recurring weekly day off. When False, all time fields must be null.",
                verbose_name="Рабочий день",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="lunch_end",
            field=models.TimeField(
                blank=True,
                help_text="Optional recurring lunch end. Must be set together with lunch_start.",
                null=True,
                verbose_name="Конец перерыва",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="lunch_start",
            field=models.TimeField(
                blank=True,
                help_text="Optional recurring lunch start. The resolver splits the working block around lunch_start..lunch_end.",
                null=True,
                verbose_name="Начало перерыва",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="Block start in tenant-local TZ. Inclusive. Required when is_working=True.",
                null=True,
                verbose_name="Начало смены",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
    ]
