# Generated by Django 5.2.5 on 2026-05-15 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_clientprofile'),
        ('tenancy', '0004_tenant_shadow_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, default='', max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('master_name', models.CharField(blank=True, default='', max_length=150)),
                ('client_name', models.CharField(max_length=150)),
                ('client_phone', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_processed', models.BooleanField(default=False, help_text='Admin-side flag. Wizard rows start False (operator calls back); yclients_admin webhook rows start True (the admin already booked it in YClients).')),
                ('source', models.CharField(choices=[('wizard', 'Wizard form on site'), ('bot', 'Bot chat flow'), ('yclients_admin', 'YClients admin (salon side)'), ('import', 'Bulk import')], default='wizard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(blank=True, help_text='Linked channel identity. SET_NULL — the booking row is still a valuable analytics record after the BotUser is purged (GDPR right-to-erasure scenario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='identity.botuser')),
                ('tenant', models.ForeignKey(help_text='Owning tenant. PROTECT — bookings are a forensic / billing artefact; deleting a tenant requires explicit data purge first (audit retention requirement).', on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Booking request',
                'verbose_name_plural': 'Booking requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yclients_record_id', models.CharField(blank=True, db_index=True, help_text='YClients record id (stringified — YClients ints fit fine but the API will return larger opaque ids on enterprise tenants per their roadmap).', max_length=64)),
                ('chat_id', models.CharField(help_text='Snapshot of BotUser.chat_id at write time. Snapshot — chat_id may change in BotUser later.', max_length=128)),
                ('visit_at', models.DateTimeField(help_text='When the actual salon visit is scheduled.')),
                ('kind', models.CharField(choices=[('day_before', 'T-24h (day before)'), ('two_hours', 'T-2h (two hours before)')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending dispatch'), ('sent_no_reply', 'Sent, no client reply yet'), ('sent', 'Sent (T-2h, no buttons)'), ('confirmed', 'Client confirmed'), ('reschedule', 'Client requested reschedule'), ('cancelled', 'Client / admin cancelled'), ('escalated', 'Escalated to human operator'), ('failed', 'Send error')], db_index=True, default='pending', max_length=16)),
                ('scheduled_at', models.DateTimeField(help_text='When this reminder should fire (visit_at minus 24h or 2h depending on `kind`).')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('master_name', models.CharField(blank=True, default='', max_length=120)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(help_text='The recipient. CASCADE: if the BotUser is purged (GDPR erasure), the reminders for that person must go too — an orphaned reminder would have nowhere to send.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_reminders', to='identity.botuser')),
                ('tenant', models.ForeignKey(help_text='Owning tenant. PROTECT mirrors BookingRequest.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_reminders', to='tenancy.tenant')),
                ('booking_request', models.ForeignKey(blank=True, help_text='Optional link to the source BookingRequest row (present when the reminder was created by our admin webhook).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='booking.bookingrequest')),
            ],
            options={
                'verbose_name': 'Booking reminder',
                'verbose_name_plural': 'Booking reminders',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['tenant', '-created_at'], name='booking_boo_tenant__39eed6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['tenant', 'bot_user'], name='booking_boo_tenant__b58315_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingreminder',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='booking_boo_tenant__c4a1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingreminder',
            index=models.Index(fields=['tenant', 'yclients_record_id'], name='booking_boo_tenant__e3cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingreminder',
            index=models.Index(fields=['kind', 'visit_at'], name='booking_boo_kind_2e50fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingreminder',
            unique_together={('yclients_record_id', 'kind')},
        ),
    ]
