# Generated by Django 5.2.14 on 2026-05-16 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        ("identity", "0002_clientprofile"),
        ("tenancy", "0005_tenant_manager_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingBookingAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirm", "Confirm booking (preview → create)"),
                            ("cancel", "Cancel booking (preview → cancel)"),
                            ("reschedule", "Reschedule booking (preview → cancel+create)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Per-kind argument bundle captured at preview time. See model docstring for the shape per kind.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Tap-after-expiry returns a polite 'too much time' reply and does NOT execute. 10-minute window per spec.",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set inside the consume CAS. Non-null → already executed (or cancelled by user tap on ❌). A second tap on the same token short-circuits to 'already handled'.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending booking action",
                "verbose_name_plural": "Pending booking actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled (replaced)"),
                ],
                db_index=True,
                default="confirmed",
                help_text="Lifecycle: confirmed (default), cancelled (customer cancel), rescheduled (replaced by a new row after a cancel-and-create reschedule).",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="bookingrequest",
            index=models.Index(fields=["tenant", "status"], name="booking_boo_tenant__20c63c_idx"),
        ),
        migrations.AddField(
            model_name="pendingbookingaction",
            name="bot_user",
            field=models.ForeignKey(
                help_text="Owner of this pending action. Authorisation check in the callback handler compares the tapping user's BotUser pk to this FK — prevents a leaked callback id from being executed by a different user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_booking_actions",
                to="identity.botuser",
            ),
        ),
        migrations.AddField(
            model_name="pendingbookingaction",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — pending rows are ephemeral (10-min TTL), no audit value in keeping after tenant deletion.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_booking_actions",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingbookingaction",
            index=models.Index(
                fields=["tenant", "bot_user"], name="booking_pen_tenant__c609c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingbookingaction",
            index=models.Index(fields=["expires_at"], name="booking_pen_expires_95c2b1_idx"),
        ),
    ]
