# Generated by Django 5.2.14 on 2026-05-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_pendingbookingaction_bookingrequest_status_and_more"),
        ("catalog", "0001_initial"),
        ("conversations", "0008_remove_conversation_conversatio_tenant__e5cdfd_idx_and_more"),
        ("identity", "0002_clientprofile"),
        ("tenancy", "0007_tenant_telegram_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="ai_assist_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0.00–1.00 internal analytics estimate of AI contribution.",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="attribution_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Audit context. Required key: actor_type (validator).",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="billable",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Locked rule: True iff booking_source='ai_direct' AND status=='confirmed'. Set once, never recomputed.",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="billing_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required when billable=True (audit trail).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("ai_direct", "AI created booking directly"),
                    ("ai_assisted", "AI participated; human finished"),
                    ("human_direct", "Salon staff only, no AI"),
                    ("external", "From outside (YClients UI, phone)"),
                    ("test_admin", "Test or admin/master-created"),
                ],
                db_index=True,
                default="external",
                help_text="Per attribution-policy. ai_direct only is billable.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="conversations.conversation",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="duration_min",
            field=models.PositiveIntegerField(
                blank=True, help_text="Service duration at booking time (snapshot).", null=True
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_requests",
                to="catalog.catalogmaster",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_requests",
                to="catalog.catalogservice",
            ),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="visit_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the appointment is scheduled. Required for new (non-external) rows; legacy backfilled rows have NULL.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "confirmed"), ("visit_at__isnull", False)),
                fields=("master", "visit_at"),
                name="booking_unique_master_confirmed_visit_at",
            ),
        ),
    ]
