# Generated by Django 5.2.5 on 2026-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_backfill_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Stamped by apps.bookings.tasks.detect_completed_bookings when the periodic scan finds the visit has ended (visit_at + duration + grace < now()) AND status is still CONFIRMED. Acts as the idempotency lock for the booking.completed eventbus producer: the task SET ... WHERE completed_at IS NULL — rowcount tells whether we won the race. NULL on rows where the visit hasn't happened yet, was cancelled, or where the producer hasn't run yet.",
                null=True,
            ),
        ),
    ]
