# Generated by Django 5.2.14 on 2026-05-19 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_cancel_reschedule_state"),
        ("booking", "0007_bookingrequest_feedback"),
    ]

    operations = []
