# Generated by Django 5.2.5 on 2026-05-22 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_merge_20260519_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="original_booking_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Q12-α continuation-chain root (issue #478, founder ACK 2026-05-22). NULL when this row starts a new billable chain (fresh ai_direct booking OR a reschedule that broke the chain via service_swap / >90d / partial-failure terminal). Set to the chain ROOT's id when this row is a continuation (same service, ≤90d from root, no intervening cancel). PROTECT so a deleted root can't silently orphan the chain. Always points at the ROOT, never at an intermediate link — see apps/booking/services/attribution.py::compute_reschedule_continuation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reschedule_continuations",
                to="booking.bookingrequest",
            ),
        ),
    ]
