# Generated by Django 5.2.5 on 2026-05-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_q12a_continuation_idx_concurrently"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="commercial_identity_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Q12-α #541 (founder ACK 2026-05-23) — snapshot of the service's commercial identity at booking write time. Used by reschedule continuation chain to break when the salon admin mutates the service (price hike, duration change, currency swap, FK relink). Schema: {service_id, service_name, sticker_price_amount, currency, duration_minutes}. Only 4 fields are compared (service_name is informational). Pre-#541 rows have NULL → chain check skipped per memory q12a-billing-founder-gate (legacy chains preserved).",
                null=True,
            ),
        ),
    ]
