# Generated by Django 5.2.14 on 2026-07-03 03:57
#
# #1066 (completes #1058 end-to-end) — widen
# RemoteBookingProxy.last_synced_event_id from varchar(26) (ULID width)
# to varchar(36) so Ayla's uuid4() (36 chars) fits. #1067 widened the
# eventbus dedupe/DLQ columns; without this one, a real 36-char booking.*
# event passes IngestDedupe but the consumer's write of
# last_synced_event_id still raises Postgres DataError → HANDLER_EXCEPTION
# → 500 → Ayla retries forever. Tech-lead authorized this cross-app touch
# in #1066.
#
# Migration safety: varchar length INCREASE only. Postgres does NOT
# rewrite the table or reindex for a varchar length increase (catalog
# atttypmod bump under a brief sub-ms ACCESS EXCLUSIVE lock; no row scan).
# No data loss; existing 26-char rows untouched. Reverse (36→26) is
# forward-safe: Postgres ABORTS loudly with "value too long" if any
# >26-char row exists — never silent truncation.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_alter_bookingreminder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="last_synced_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cross-service event_id (bare ULID 26 chars or Ayla uuid4 36 chars, #1058) of the last event that touched this row. Forensic trace, not the primary idempotency key (that's the IngestDedupe table on the ingest side).",
                max_length=36,
            ),
        ),
    ]
