# Generated by Django 5.2.14 on 2026-07-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0014_widen_event_id_to_36"),
        ("tenancy", "0010_tenant_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMirror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Canonical Ayla Appointment.id the payment belongs to.",
                    ),
                ),
                (
                    "payment_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Ayla Payment.id. Null for the hold signal when the booking.confirmed payload omits it.",
                        null=True,
                    ),
                ),
                (
                    "capture_state",
                    models.CharField(
                        choices=[
                            ("authorized", "Hold (booking.confirmed)"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("canceled", "Canceled / released"),
                        ],
                        help_text="Last known capture state from the event stream.",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment amount (Decimal, 2dp per §1).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_synced_event_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="event_id of the last event that touched this row (forensic trace; IngestDedupe is the primary idempotency).",
                        max_length=36,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — mirror is derived data.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_mirrors",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment mirror",
                "verbose_name_plural": "Payment mirrors",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "appointment_id"),
                        name="uq_payment_mirror_tenant_appointment",
                    )
                ],
            },
        ),
    ]
