# Generated by Django 5.2.14 on 2026-07-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0015_paymentmirror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("pending_payment", "Pending payment"),
                    ("tentative", "Tentative"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No show"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
