"""Кто закрыл визит — колонка на обеих сторонах (решение владельца 30.08).

Схемная правка, без бэкфилла, и это выбор, а не пропуск.

Существующие закрытые строки получают ``""``. Читатель
(:func:`apps.booking.completion.confirmed_by_human`) считает пустое
значение неподтверждённым, то есть все визиты, закрытые до этой
миграции, перестают тянуть за собой баллы и запрос отзыва.

Для ``BookingRequest`` это не приближение, а точный ответ:
``completed_at`` там пишет ровно один код —
``apps.bookings.tasks.detect_completed_bookings``, часы. Каждая уже
закрытая строка закрыта системой, и ``""`` читается ровно так.

Для ``RemoteBookingProxy`` ответ неизвестен: событие ``booking.completed``
до этого коммита не сохраняло актора, и восстановить его из зеркала
нечем. Бэкфилл значением ``master`` выдал бы догадку за подтверждение —
ровно та подмена, из-за которой заведена эта ветка. Бэкфилл значением
``system`` выглядел бы честнее, но соврал бы про визиты, которые мастер
действительно закрыл руками. Пустое значение не утверждает ни того, ни
другого и ошибается в сторону молчания.

"""

# Generated by Django 5.2.14 on 2026-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0019_remotebookingproxy_normalize_awaiting_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто закрыл визит. ``system`` — закрытие по часам (apps.bookings.tasks.detect_completed_bookings); имя человека — подтверждение, что клиент пришёл. Пустое на незакрытых строках и на строках, закрытых до этого поля. Читается через apps.booking.completion.confirmed_by_human: последствия, требующие подтверждения визита (баллы, запрос отзыва), наступают только на человеческом значении — решение владельца 30.08. ``completed_at`` отвечает «визит закрыт?», это поле — «человек пришёл?»; до 30.08 первый ответ выдавали за второй.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="remotebookingproxy",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто закрыл визит на стороне Ayla — зеркало поля ``completed_by`` из полезной нагрузки ``booking.completed`` и ``/tenants/me/day/``. ``system`` = трёхчасовое автозакрытие по часам, никто не подтверждал, что клиент пришёл. Пустое, пока визит не завершён. Единственный читатель на нашей стороне, который может отличить «часы досчитали» от «мастер подтвердил»: ``status=completed`` одинаков для обоих. Последствия, требующие подтверждения визита, гейтятся по нему (решение владельца 30.08) — см. apps.booking.completion.",
                max_length=64,
            ),
        ),
    ]
