# Generated by Django 5.2.14 on 2026-09-08 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_completed_by_actor"),
        ("catalog", "0019_master_address_and_location"),
        ("conversations", "0016_conversation_anonymized_reason_and_more"),
        ("identity", "0022_botuser_blocked_at_botuser_blocked_by_username_and_more"),
        ("tenancy", "0015_tenant_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingreminder",
            options={
                "ordering": ["scheduled_at"],
                "verbose_name": "Напоминание о записи",
                "verbose_name_plural": "Напоминания о записях",
            },
        ),
        migrations.AlterModelOptions(
            name="bookingrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запись клиента",
                "verbose_name_plural": "Записи клиентов",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmirror",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Платёж (зеркало)",
                "verbose_name_plural": "Платежи (зеркало)",
            },
        ),
        migrations.AlterModelOptions(
            name="pendingbookingaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отложенное действие по записи",
                "verbose_name_plural": "Отложенные действия по записям",
            },
        ),
        migrations.AlterModelOptions(
            name="remotebookingproxy",
            options={
                "ordering": ["-start_at"],
                "verbose_name": "Визит в Ayla (зеркало)",
                "verbose_name_plural": "Визиты в Ayla (зеркало)",
            },
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="ayla_appointment_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Ayla appointment UUID per ADR-0009 event contract. When set, replaces yclients_record_id as the idempotency key for Ayla-side reminders (#442 booking consumer). Coexists with the YClients legacy path: rows from the YClients webhook keep yclients_record_id + leave this nullable; rows from the Ayla consumer set this + leave yclients_record_id blank.",
                null=True,
                verbose_name="Идентификатор визита в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="booking_request",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the source BookingRequest row (present when the reminder was created by our admin webhook).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminders",
                to="booking.bookingrequest",
                verbose_name="Запись",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="bot_user",
            field=models.ForeignKey(
                help_text="The recipient. CASCADE: if the BotUser is purged (GDPR erasure), the reminders for that person must go too — an orphaned reminder would have nowhere to send.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_reminders",
                to="identity.botuser",
                verbose_name="Аккаунт клиента в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="chat_id",
            field=models.CharField(
                help_text="Snapshot of BotUser.chat_id at write time. Snapshot — chat_id may change in BotUser later.",
                max_length=128,
                verbose_name="Идентификатор диалога",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("day_before", "T-24h (day before)"),
                    ("two_hours", "T-2h (two hours before)"),
                ],
                max_length=16,
                verbose_name="Вид напоминания",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="master_name",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Мастер"
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="replied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Клиент ответил"
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="scheduled_at",
            field=models.DateTimeField(
                help_text="When this reminder should fire (visit_at minus 24h or 2h depending on `kind`).",
                verbose_name="Отправить в",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отправлено"
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="service_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Услуга"
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending dispatch"),
                    ("sent_no_reply", "Sent, no client reply yet"),
                    ("sent", "Sent (T-2h, no buttons)"),
                    ("confirmed", "Client confirmed"),
                    ("reschedule", "Client requested reschedule"),
                    ("cancelled", "Client / admin cancelled"),
                    ("escalated", "Escalated to human operator"),
                    ("failed", "Send error"),
                    ("stale_dropped", "Dropped at dispatch (booking changed)"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Состояние напоминания",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. PROTECT mirrors BookingRequest.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_reminders",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="visit_at",
            field=models.DateTimeField(
                help_text="When the actual salon visit is scheduled.",
                verbose_name="Время визита",
            ),
        ),
        migrations.AlterField(
            model_name="bookingreminder",
            name="yclients_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="YClients record id (stringified — YClients ints fit fine but the API will return larger opaque ids on enterprise tenants per their roadmap). Nullable so the Ayla consumer path (#442) writes NULL here while the legacy unique_together (yclients_record_id, kind) stays non-conflicting — NULL ≠ NULL in Postgres uniqueness, so two Ayla appointments with the same kind don't collide.",
                max_length=64,
                null=True,
                verbose_name="Идентификатор записи в YClients",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="ai_assist_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0.00–1.00 internal analytics estimate of AI contribution.",
                max_digits=3,
                verbose_name="Вклад ассистента",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="attribution_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Audit context. Required key: actor_type (validator).",
                verbose_name="Данные атрибуции",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="billable",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Locked rule: True iff booking_source='ai_direct' AND status=='confirmed'. Set once, never recomputed.",
                verbose_name="Тарифицируется",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="billing_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required when billable=True (audit trail).",
                max_length=200,
                verbose_name="Причина тарификации",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("ai_direct", "AI created booking directly"),
                    ("ai_assisted", "AI participated; human finished"),
                    ("human_direct", "Salon staff only, no AI"),
                    ("external", "From outside (YClients UI, phone)"),
                    ("test_admin", "Test or admin/master-created"),
                ],
                db_index=True,
                default="external",
                help_text="Per attribution-policy. ai_direct only is billable.",
                max_length=20,
                verbose_name="Канал записи",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="bot_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked channel identity. SET_NULL — the booking row is still a valuable analytics record after the BotUser is purged (GDPR right-to-erasure scenario).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_requests",
                to="identity.botuser",
                verbose_name="Аккаунт клиента в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="cancel_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when state flips to CANCEL_REQUESTED. Used to compute the undo window expiry (5s per customer-cancellation-reschedule-spec §3.4 / Q-CR1).",
                null=True,
                verbose_name="Отмена запрошена",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="category_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Категория (как было при записи)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="client_name",
            field=models.CharField(max_length=150, verbose_name="Имя клиента"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="client_phone",
            field=models.CharField(max_length=30, verbose_name="Телефон клиента"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="commercial_identity_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Q12-α #541 (founder ACK 2026-05-23) — snapshot of the service's commercial identity at booking write time. Used by reschedule continuation chain to break when the salon admin mutates the service (price hike, duration change, currency swap, FK relink). Schema: {service_id, service_name, sticker_price_amount, currency, duration_minutes}. Only 4 fields are compared (service_name is informational). Pre-#541 rows have NULL → chain check skipped per memory q12a-billing-founder-gate (legacy chains preserved).",
                null=True,
                verbose_name="Снимок коммерческих признаков",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Stamped by apps.bookings.tasks.detect_completed_bookings when the periodic scan finds the visit has ended (visit_at + duration + grace < now()) AND status is still CONFIRMED. Acts as the idempotency lock for the booking.completed eventbus producer: the task SET ... WHERE completed_at IS NULL — rowcount tells whether we won the race. NULL on rows where the visit hasn't happened yet, was cancelled, or where the producer hasn't run yet.",
                null=True,
                verbose_name="Визит завершён",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто закрыл визит. ``system`` — закрытие по часам (apps.bookings.tasks.detect_completed_bookings); имя человека — подтверждение, что клиент пришёл. Пустое на незакрытых строках и на строках, закрытых до этого поля. Читается через apps.booking.completion.confirmed_by_human: последствия, требующие подтверждения визита (баллы, запрос отзыва), наступают только на человеческом значении — решение владельца 30.08. ``completed_at`` отвечает «визит закрыт?», это поле — «человек пришёл?»; до 30.08 первый ответ выдавали за второй.",
                max_length=64,
                verbose_name="Кто отметил завершение",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="conversations.conversation",
                verbose_name="Диалог",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="duration_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Service duration at booking time (snapshot).",
                null=True,
                verbose_name="Длительность, мин",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="feedback_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Wall-clock when the rating was submitted. Idempotency anchor: submit_feedback raises 'already_rated' when this is non-NULL.",
                null=True,
                verbose_name="Отзыв оставлен",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="feedback_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional free-text comment from the F5 form (≤500 chars enforced at the API).",
                verbose_name="Отзыв клиента",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="feedback_prompt_sent_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the post-visit DM prompt was dispatched. NULL = not yet sent. Phase 4b will scan WHERE NULL and visit_at < now()-1h.",
                null=True,
                verbose_name="Просьба об отзыве отправлена",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор записи",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Admin-side flag. Wizard rows start False (operator calls back); yclients_admin webhook rows start True (the admin already booked it in YClients).",
                verbose_name="Обработана оператором",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_requests",
                to="catalog.catalogmaster",
                verbose_name="Мастер (связь с каталогом)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="master_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Мастер (как было при записи)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="original_booking_event",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                help_text="Q12-α continuation-chain root (issue #478, founder ACK 2026-05-22). NULL when this row starts a new billable chain (fresh ai_direct booking OR a reschedule that broke the chain via service_swap / >90d / partial-failure terminal). Set to the chain ROOT's id when this row is a continuation (same service, ≤90d from root, no intervening cancel). PROTECT so a deleted root can't silently orphan the chain. Always points at the ROOT, never at an intermediate link — see apps/booking/services/attribution.py::compute_reschedule_continuation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reschedule_continuations",
                to="booking.bookingrequest",
                verbose_name="Исходное событие записи",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Customer rating 1-5. NULL until they submit the F5 form. Values <= 3 fire the handoff flow.",
                null=True,
                verbose_name="Оценка клиента",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="reschedule_candidate",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stashed candidate slot for an in-flight reschedule: {'new_master_id', 'new_service_id', 'new_visit_at'}. Cleared on commit/abandon.",
                verbose_name="Кандидат на перенос",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="rescheduled_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Self-FK: the old BookingRequest this row replaced after a customer-initiated reschedule. PROTECT so the audit linkage cannot be silently broken by deleting the old row.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rescheduled_into",
                to="booking.bookingrequest",
                verbose_name="Перенесена из записи",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_requests",
                to="catalog.catalogservice",
                verbose_name="Услуга (связь с каталогом)",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="service_name",
            field=models.CharField(
                max_length=200, verbose_name="Услуга (как было при записи)"
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="source",
            field=models.CharField(
                choices=[
                    ("wizard", "Wizard form on site"),
                    ("bot", "Bot chat flow"),
                    ("yclients_admin", "YClients admin (salon side)"),
                    ("import", "Bulk import"),
                ],
                default="wizard",
                max_length=20,
                verbose_name="Откуда пришла запись",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancel_requested", "Cancel requested (within undo window)"),
                    (
                        "reschedule_requested",
                        "Reschedule requested (candidate stashed)",
                    ),
                    ("cancelled", "Cancelled"),
                    ("rescheduled", "Rescheduled (replaced)"),
                ],
                db_index=True,
                default="confirmed",
                help_text="Lifecycle: confirmed (default) → cancel_requested → cancelled OR reschedule_requested → rescheduled. cancel_requested and reschedule_requested are interim states reversible by the customer.",
                max_length=24,
                verbose_name="Состояние записи",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. PROTECT — bookings are a forensic / billing artefact; deleting a tenant requires explicit data purge first (audit retention requirement).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_requests",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="visit_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the appointment is scheduled. Required for new (non-external) rows; legacy backfilled rows have NULL.",
                null=True,
                verbose_name="Время визита",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Payment amount (Decimal, 2dp per §1).",
                max_digits=10,
                null=True,
                verbose_name="Сумма",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="appointment_id",
            field=models.UUIDField(
                db_index=True,
                help_text="Canonical Ayla Appointment.id the payment belongs to.",
                verbose_name="Идентификатор визита в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="capture_state",
            field=models.CharField(
                choices=[
                    ("authorized", "Hold (booking.confirmed)"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("canceled", "Canceled / released"),
                ],
                help_text="Last known capture state from the event stream.",
                max_length=16,
                verbose_name="Состояние платежа",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="last_synced_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="event_id of the last event that touched this row (forensic trace; IngestDedupe is the primary idempotency).",
                max_length=36,
                verbose_name="Последнее применённое событие",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="payment_id",
            field=models.UUIDField(
                blank=True,
                help_text="Ayla Payment.id. Null for the hold signal when the booking.confirmed payload omits it.",
                null=True,
                verbose_name="Идентификатор платежа в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — mirror is derived data.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_mirrors",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmirror",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="bot_user",
            field=models.ForeignKey(
                help_text="Owner of this pending action. Authorisation check in the callback handler compares the tapping user's BotUser pk to this FK — prevents a leaked callback id from being executed by a different user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_booking_actions",
                to="identity.botuser",
                verbose_name="Аккаунт клиента в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set inside the consume CAS. Non-null → already executed (or cancelled by user tap on ❌). A second tap on the same token short-circuits to 'already handled'.",
                null=True,
                verbose_name="Использовано",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="expires_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="Tap-after-expiry returns a polite 'too much time' reply and does NOT execute. 10-minute window per spec.",
                verbose_name="Действует до",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirm booking (preview → create)"),
                    ("cancel", "Cancel booking (preview → cancel)"),
                    ("reschedule", "Reschedule booking (preview → cancel+create)"),
                ],
                max_length=16,
                verbose_name="Вид действия",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Per-kind argument bundle captured at preview time. See model docstring for the shape per kind.",
                verbose_name="Данные действия",
            ),
        ),
        migrations.AlterField(
            model_name="pendingbookingaction",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — pending rows are ephemeral (10-min TTL), no audit value in keeping after tenant deletion.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_booking_actions",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="appointment_id",
            field=models.UUIDField(
                editable=False,
                help_text="Canonical Ayla djangoproject Appointment.id (UUID).",
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор визита в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="bot_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Channel-side user identity. Nullable: an Ayla mobile-only customer can have bookings before ever opening the bot, so the proxy is written orphan and a post_save signal on BotUser backfills the ref when the user appears via any channel. CASCADE applies only to the linked case: if the BotUser is purged (GDPR erasure), linked mirrors go too — orphan rows are unaffected (no link to cascade through).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_booking_proxies",
                to="identity.botuser",
                verbose_name="Аккаунт клиента в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="client_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Same claim, for the client-facing «вы записаны» confirmation (DRF-1066), taken by whichever handler decides to send it. Stays NULL for a booking made in the bot's own dialog: there ``execute_confirm`` already answered in chat, this channel deliberately says nothing, and the chat-origin marker — not this column — is what keeps it silent.",
                null=True,
                verbose_name="Клиент уведомлён",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="completed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Кто закрыл визит на стороне Ayla — зеркало поля ``completed_by`` из полезной нагрузки ``booking.completed`` и ``/tenants/me/day/``. ``system`` = трёхчасовое автозакрытие по часам, никто не подтверждал, что клиент пришёл. Пустое, пока визит не завершён. Единственный читатель на нашей стороне, который может отличить «часы досчитали» от «мастер подтвердил»: ``status=completed`` одинаков для обоих. Последствия, требующие подтверждения визита, гейтятся по нему (решение владельца 30.08) — см. apps.booking.completion.",
                max_length=64,
                verbose_name="Кто отметил завершение",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="end_at",
            field=models.DateTimeField(
                help_text="Appointment end. Round-3 spec §3.3: reschedule preserves duration via ``new_end_at = new_start_at + (old_end_at - old_start_at)`` — this field is what the math reads.",
                verbose_name="Окончание визита",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="last_applied_appointment_version",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Highest canonical `appointment.rescheduled` DER `version` applied to this proxy (AYLA-DEC-0022/0036 version-aware ordering). NULL means no canonical version-tracked event has been applied yet — proxies created or updated only via legacy booking.created/booking.rescheduled never set this field. See apps.eventbus.consumers.booking.handle_appointment_rescheduled_canonical for the ordering state machine (bootstrap / skip / apply / gap).",
                null=True,
                verbose_name="Версия визита",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="last_synced_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cross-service event_id (bare ULID 26 chars or Ayla uuid4 36 chars, #1058) of the last event that touched this row. Forensic trace, not the primary idempotency key (that's the IngestDedupe table on the ingest side).",
                max_length=36,
                verbose_name="Последнее применённое событие",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="salon_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a handler claimed the one-shot salon announcement for this appointment (DRF-1030 / DRF-1069). NULL = nobody on the salon side has been told yet. Set inside the ingest transaction, before the after-commit send: a rolled-back ingest releases the claim, a re-delivered event finds it taken. Records the claim, not delivery — the send itself is best-effort and may still find no reachable recipient.",
                null=True,
                verbose_name="Салон уведомлён",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Ayla Service.id — looked up via catalog mirror for the AI to say 'у тебя стрижка'. Nullable because update events (cancelled / rescheduled / completed) don't repeat the service reference; the row keeps the value set at creation time.",
                null=True,
                verbose_name="Услуга (идентификатор в Ayla)",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile_app", "Mobile app"),
                    ("admin_console", "Admin console"),
                    ("automation", "Automation"),
                    ("yclients_sync", "YClients sync"),
                ],
                default="",
                help_text="Where the booking originated. Empty when source isn't carried in the event (booking.cancelled / .rescheduled / .completed don't repeat the source).",
                max_length=20,
                verbose_name="Откуда визит",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="specialist_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Ayla Master.id — analogous to ``service_id``.",
                null=True,
                verbose_name="Мастер (идентификатор в Ayla)",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="start_at",
            field=models.DateTimeField(
                db_index=True,
                help_text="Appointment start, salon-local timezone. Reminder math (T-24h / T-2h) computes against this.",
                verbose_name="Начало визита",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("pending_payment", "Pending payment"),
                    ("tentative", "Tentative"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No show"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Состояние визита",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the platform last updated this row.",
                verbose_name="Синхронизировано",
            ),
        ),
        migrations.AlterField(
            model_name="remotebookingproxy",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — the proxy is derived data; if the tenant goes, the local mirror goes too.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remote_booking_proxies",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
    ]
