# Generated by Django 5.2.17 on 2026-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0021_alter_bookingreminder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingreminder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending dispatch"),
                    ("sent_no_reply", "Sent, no client reply yet"),
                    ("sent", "Sent (T-2h, no buttons)"),
                    ("confirmed", "Client confirmed"),
                    ("reschedule", "Client requested reschedule"),
                    ("cancelled", "Client / admin cancelled"),
                    ("escalated", "Escalated to human operator"),
                    ("failed", "Send error"),
                    ("stale_dropped", "Dropped at dispatch (booking changed)"),
                    ("muted", "Muted by the person (notify_reminders off)"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
                verbose_name="Состояние напоминания",
            ),
        ),
    ]
