# Generated by Django 5.2.14 on 2026-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0022_bookingreminder_muted_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotebookingproxy",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Snapshot of booking.created.price_total; NULL when the event carried none.",
                max_digits=10,
                null=True,
                verbose_name="Цена записи (снимок)",
            ),
        ),
    ]
