# Generated by Django 5.2.14 on 2026-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0023_remotebookingproxy_price_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="remotebookingproxy",
            name="last_applied_event_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда канон выпустил последнее применённое событие (``occurred_at`` конверта, DRF-2537). NULL — неизвестно, обратно не заполняется. Не свежесть: пропущенное событие эту отметку не двигает.",
                null=True,
                verbose_name="Время события канона",
            ),
        ),
        migrations.AddField(
            model_name="remotebookingproxy",
            name="last_applied_event_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Имя последнего применённого события канона (DRF-2537). Пусто — неизвестно: строка до DRF-2537 или записана самим ботом.",
                max_length=64,
                verbose_name="Последнее событие канона",
            ),
        ),
    ]
