# Generated by Django 5.2.14 on 2026-05-11 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the human actor, if any. Null for system events.",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Namespaced verb, e.g. tenant.created, cross_tenant.attempt.",
                        max_length=120,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name of the affected entity (Tenant, Conversation, ...).",
                        max_length=80,
                    ),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra structured data. Never store raw PII; store IDs and hashes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant in scope at the time of the event. Null for system events (tenant rotation, breaker state changes).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log",
                "verbose_name_plural": "Audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="audit_audit_tenant__1d7666_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"
                    ),
                ],
            },
        ),
    ]
