# Generated by Django 5.2.14 on 2026-06-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_payload_gin_concurrently"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_audit_is_arch_4b93a0_idx",
            old_name="audit_auditl_is_arch_idx",
        ),
    ]
