# Generated by Django 5.2.14 on 2026-05-13 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_features_tenant_locale_tenant_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogFaq",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.IntegerField(
                        help_text="Primary key of the upstream mysite row. Stable; the sync upserter (C3 / DRF-574) matches on (tenant, external_id)."
                    ),
                ),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5)."
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("category_slug", models.SlugField(blank=True, default="", max_length=100)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog: FAQ",
                "verbose_name_plural": "Catalog: FAQs",
                "ordering": ["question"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-external_updated_at"],
                        name="catalog_cat_tenant__8fd2f3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "category_slug"], name="catalog_cat_tenant__713735_idx"
                    ),
                ],
                "unique_together": {("tenant", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="CatalogHelpArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.IntegerField(
                        help_text="Primary key of the upstream mysite row. Stable; the sync upserter (C3 / DRF-574) matches on (tenant, external_id)."
                    ),
                ),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5)."
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog: help article",
                "verbose_name_plural": "Catalog: help articles",
                "ordering": ["order", "question"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-external_updated_at"],
                        name="catalog_cat_tenant__86e006_idx",
                    ),
                    models.Index(
                        fields=["tenant", "is_active", "order"],
                        name="catalog_cat_tenant__5013cb_idx",
                    ),
                ],
                "unique_together": {("tenant", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="CatalogMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.IntegerField(
                        help_text="Primary key of the upstream mysite row. Stable; the sync upserter (C3 / DRF-574) matches on (tenant, external_id)."
                    ),
                ),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5)."
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specialization", models.CharField(blank=True, default="", max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                ("experience", models.CharField(blank=True, default="", max_length=255)),
                (
                    "rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "yclients_staff_id",
                    models.IntegerField(
                        blank=True,
                        help_text="YClients staff id — pre-populated from mysite so the Phase 1 booking flow can dispatch without a second lookup.",
                        null=True,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog: master",
                "verbose_name_plural": "Catalog: masters",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-external_updated_at"],
                        name="catalog_cat_tenant__603650_idx",
                    ),
                    models.Index(
                        fields=["tenant", "yclients_staff_id"],
                        name="catalog_cat_tenant__77675f_idx",
                    ),
                ],
                "unique_together": {("tenant", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="CatalogService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "external_id",
                    models.IntegerField(
                        help_text="Primary key of the upstream mysite row. Stable; the sync upserter (C3 / DRF-574) matches on (tenant, external_id)."
                    ),
                ),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5)."
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("short_description", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price_from",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("duration_min", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, default="", max_length=255)),
                ("seo_description", models.TextField(blank=True, default="")),
                ("goals", models.JSONField(blank=True, default=list)),
                ("requires_health_check", models.BooleanField(default=False)),
                ("contraindications", models.TextField(blank=True, default="")),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog: service",
                "verbose_name_plural": "Catalog: services",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-external_updated_at"],
                        name="catalog_cat_tenant__5ddf78_idx",
                    ),
                    models.Index(fields=["tenant", "slug"], name="catalog_cat_tenant__035e07_idx"),
                ],
                "unique_together": {("tenant", "external_id")},
            },
        ),
    ]
