# Generated by Django 5.2.14 on 2026-05-18 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0007_tenant_telegram_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catalog: master-service mapping",
                "verbose_name_plural": "Catalog: master-service mappings",
                "ordering": ["master_id", "service_id"],
            },
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending invite"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="accepted",
                help_text="Default ACCEPTED so backfilled/sync masters are bookable. Invite create-path writes PENDING.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="max_handle",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="mode",
            field=models.CharField(
                choices=[
                    ("invite", "Invite-based access"),
                    ("catalog_only", "Catalog only (no login)"),
                ],
                default="catalog_only",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="photo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddIndex(
            model_name="catalogmaster",
            index=models.Index(
                fields=["tenant", "is_active", "invite_status"],
                name="catalog_cat_tenant__57a2ce_idx",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_offered",
                to="catalog.catalogmaster",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masters_offering",
                to="catalog.catalogservice",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master_services",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="masterservice",
            index=models.Index(fields=["tenant", "master"], name="catalog_mas_tenant__f0b38c_idx"),
        ),
        migrations.AddIndex(
            model_name="masterservice",
            index=models.Index(fields=["tenant", "service"], name="catalog_mas_tenant__80153c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="masterservice",
            unique_together={("master", "service")},
        ),
    ]
