# Generated by Django 5.2.5 on 2026-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_catalogmaster_archive_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogservice",
            name="ayla_service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla Service.id (UUID). Lookup key for the apps/eventbus service.updated consumer. Coexists with legacy integer external_id while mysite sync still runs; a separate cleanup PR removes external_id once mysite is fully retired.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="catalogservice",
            name="cache_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mirror-staleness counter, incremented on every service.updated event. Downstream cache layers include it in their cache key so increments transparently invalidate stale entries. No active cache reads it today.",
            ),
        ),
    ]
