# Generated by Django 5.2.14 on 2026-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_catalogservice_ayla_service_id_cache_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="ayla_user_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla user_id (UUID) for this master. Bridge for event-payload master_user_id → CatalogMaster ORM JOIN. Nullable because legacy mysite-synced rows lack this — back-filled by catalog-sync service or master event consumer.",
                null=True,
            ),
        ),
    ]
