# Generated by Django 5.2.14 on 2026-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_catalogmaster_ayla_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="cache_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Slot-cache staleness counter, incremented on every master.schedule.updated event. Future cache layers (Redis, in-memory) include this in their key so increments transparently invalidate stale slot lookups. No active cache layer reads this today — it's a forward-compatible signal.",
            ),
        ),
    ]
