# Generated by Django 5.2.14 on 2026-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_catalogmaster_cache_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="review_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of reviews backing ``rating``, mirrored from Ayla's ``reviews_count``. Feeds the discovery Bayesian trust-score (#1060) so a 5.0 from 1 review can't outrank a 4.8 from 200. Populated by catalog sync once retargeted to Ayla (#1044); defaults to 0 until then.",
            ),
        ),
    ]
