# Generated by Django 5.2.14 on 2026-07-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_catalogmaster_review_count"),
        ("tenancy", "0010_tenant_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogfaq",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ayla_service_id__isnull", False)),
                fields=("tenant", "ayla_service_id"),
                name="uq_catalog_service_tenant_ayla_service_id",
            ),
        ),
    ]
