# Generated by Django 5.2.14 on 2026-07-13 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_catalogfaq_external_id_and_more"),
        ("identity", "0014_seed_global_bot_tenant"),
        ("tenancy", "0010_tenant_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="masterservice",
            name="ayla_specialist_service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla SpecialistService.id (UUID) — the **bookable** unit the bot books against (S2). Nullable for legacy/admin rows; partial-unique per tenant when set.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Bookability of this edge (Ayla specialist-services.is_active). The S2 booking flip must exclude is_active=False edges — a deactivated bookable stays mirrored (upsert-only, no tombstone) but not bookable.",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specialist price for this service (Ayla specialist-services).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="resolved_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Effective duration (min) resolved Ayla-side (specialist → salon → template). Stored as-is — never recomputed here.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="resolved_requires_health_check",
            field=models.BooleanField(
                default=False,
                help_text="Effective health gate resolved Ayla-side (OR of template floor, salon, specialist). The booking gate (#1034) reads THIS, not the salon-level CatalogService.requires_health_check.",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogmaster",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ayla_user_id__isnull", False)),
                fields=("tenant", "ayla_user_id"),
                name="uq_catalog_master_tenant_ayla_user_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="masterservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ayla_specialist_service_id__isnull", False)),
                fields=("tenant", "ayla_specialist_service_id"),
                name="uq_master_service_tenant_ayla_specialist_service_id",
            ),
        ),
    ]
