# Generated by Django 5.2.14 on 2026-08-08 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_alter_catalogfaq_external_id_and_more"),
        ("tenancy", "0010_tenant_city"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="masterservice",
            name="ayla_specialist_service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla SpecialistService.id (UUID) — the bookable master↔service edge. NULL means the row was created by an operator (MM4 matrix / invite seeding) and catalog sync must never reconcile it away.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="masterservice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ayla_specialist_service_id__isnull", False)),
                fields=("tenant", "ayla_specialist_service_id"),
                name="uq_master_service_tenant_ayla_specialist_service_id",
            ),
        ),
    ]
