# Generated by Django 5.2.14 on 2026-09-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_masterservice_write_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Момент, когда мастер впервые оказалась связанной с BotUser и принявшей приглашение — состояние M1 из docs/design/policies/master-onboarding-m0-m7.md §4.1. Ставит его ``save()`` (см. ниже), поэтому забыть его на новом пути приземления нельзя. Не стирается: это дата события, а не флаг. NULL у синхронизированных мастеров — они в бот не приземлялись.",
                null=True,
            ),
        ),
    ]
