# Generated by Django 5.2.14 on 2026-09-06 06:14

from django.db import migrations, models


def _grandfather_synced_masters(apps, schema_editor):
    """Зафиксировать осознанное решение по существующим записям (DRF-1496).

    До этой миграции ``invite_status`` по умолчанию был ``accepted``, и
    мастер, приехавший синхронизацией, рождался «принявшим приглашение»,
    которого ему никто не отправлял. Переключить умолчание вслепую —
    значит немедленно сделать небронируемыми всех девятерых мастеров
    пилота (замер 04.09.2026) и обрушить подбор.

    Поэтому существующие строки НЕ трогаем: мастера, которые сегодня
    реально принимают записи, остаются ``accepted`` — это их честное
    рабочее состояние, подтверждённое владельцем пилота. Решение
    фиксируется строкой в ``audit_auditlog``, чтобы «почему эти accepted»
    читалось из журнала, а не из памяти. Число печатается в вывод
    ``migrate`` — замер «бронируемо до/после» не молчит.

    Новые строки (синхронизация, ручное заведение) с этого момента
    рождаются ``pending`` и не бронируются, пока оператор не
    верифицирует мастера вручную через админку (тоже с журналом).
    """
    CatalogMaster = apps.get_model("catalog", "CatalogMaster")
    AuditLog = apps.get_model("audit", "AuditLog")

    grandfathered = list(
        CatalogMaster.objects.filter(
            invite_status="accepted",
            linked_bot_user__isnull=True,
        ).values_list("pk", flat=True)
    )
    total = CatalogMaster.objects.count()
    # Замер ДО смены умолчания: все эти строки бронируемы и остаются
    # бронируемыми — число после миграции обязано совпасть.
    print(  # noqa: T201 — вывод migrate и есть канал замера для выкладки
        "DRF-1496: мастеров всего=%d, из них accepted без привязки к боту "
        "(приехали синхронизацией)=%d — оставлены accepted осознанным "
        "решением, бронируемость не меняется." % (total, len(grandfathered))
    )
    if not grandfathered:
        return
    AuditLog.objects.create(
        action="catalog.masters_grandfathered",
        target="catalog.catalogmaster",
        payload={
            "count": len(grandfathered),
            "master_ids": [str(pk) for pk in grandfathered],
            "note": (
                "DRF-1496: умолчание invite_status сменено на pending; "
                "существующие accepted-мастера без linked_bot_user "
                "(приехали синхронизацией, приглашения им не слали) "
                "оставлены accepted, чтобы не обрушить подбор на пилоте. "
                "Верификация новых мастеров — вручную через админку."
            ),
            "source": "migration_0016",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_backfill_master_accepted_at"),
        ("audit", "0004_rename_audit_auditl_is_arch_idx_audit_audit_is_arch_4b93a0_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogmaster",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending invite"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Default PENDING (DRF-1496): a master born by sync was never invited, so she is not bookable until an operator verifies her by hand (journaled admin action). The pre-DRF-1496 default was ACCEPTED; rows that existed on 04.09.2026 were grandfathered as ACCEPTED by migration 0016 so the pilot's booking pick-list did not silently collapse. Invite create-path writes PENDING explicitly, as before.",
                max_length=16,
            ),
        ),
        # Данных не меняет: существующие accepted-строки остаются как
        # есть. Пишет строку в журнал аудита и печатает замер — см.
        # докстринг функции.
        migrations.RunPython(
            _grandfather_synced_masters,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
