"""DRF-1535 — help_text only, zero SQL.

Both operations change nothing but the ``help_text`` strings on
``CatalogMaster.rating`` / ``.review_count``: ``review_count`` used to
promise a discovery Bayesian trust-score that was never built, and
``rating`` said nothing about 0.00 meaning «no rating yet» (owner decision
06.09.2026, ``docs/OPEN_DECISIONS.md`` §29.4).

``help_text`` lives in Python, not in Postgres, so ``sqlmigrate`` on this
file is empty. It exists only to keep ``makemigrations --check`` (the CI
drift guard) green. Nothing breaks while it sits unapplied.
"""

# Generated by Django 5.2.14 on 2026-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_master_invite_default_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogmaster",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mirrored from the source feed. Domain is 1..5, so a stored 0.00 means «no rating yet», not «rated zero» — it is never rendered (DRF-1224) and takes no part in discovery ordering (DRF-1535).",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="review_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of reviews backing ``rating``, mirrored from Ayla's ``reviews_count``. Written by catalog sync (``catalog/services/upserter._master_fields``) and read by nobody: discovery neither ranks nor filters on it, and there is no trust-score behind it. Collecting reviews is DRF-1527; until that lands this is 0 on every pilot row.",
            ),
        ),
    ]
