# Generated by Django 5.2.14 on 2026-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_alter_catalogmaster_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Адрес мастера, зеркалится из ключа ``address`` фида специалистов. NULL — ключа в слепке не было (не знаем); "" — ключ был и нёс пустое (источник ответил «нет»). Разница обязательна: подставленное значение неотличимо от настоящего.',
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="location_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Широта из ключа ``location_lat``. NULL — координаты нет (ключ отсутствовал либо нёс null). НИКОГДА не 0.0: пара нулей — точка в Гвинейском заливе, неотличимая от настоящей.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="location_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Долгота из ключа ``location_lng``. NULL — координаты нет (ключ отсутствовал либо нёс null). НИКОГДА не 0.0 — см. ``location_lat``.",
                max_digits=9,
                null=True,
            ),
        ),
    ]
