# Generated by Django 5.2.14 on 2026-09-08 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_master_address_and_location"),
        ("identity", "0022_botuser_blocked_at_botuser_blocked_by_username_and_more"),
        ("tenancy", "0015_tenant_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogfaq",
            options={
                "ordering": ["question"],
                "verbose_name": "Вопрос и ответ",
                "verbose_name_plural": "Вопросы и ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="cataloghelparticle",
            options={
                "ordering": ["order", "question"],
                "verbose_name": "Статья справки",
                "verbose_name_plural": "Статьи справки",
            },
        ),
        migrations.AlterModelOptions(
            name="catalogmaster",
            options={
                "ordering": ["name"],
                "verbose_name": "Мастер",
                "verbose_name_plural": "Мастера",
            },
        ),
        migrations.AlterModelOptions(
            name="catalogservice",
            options={
                "ordering": ["name"],
                "verbose_name": "Услуга каталога",
                "verbose_name_plural": "Услуги каталога",
            },
        ),
        migrations.AlterModelOptions(
            name="masterservice",
            options={
                "ordering": ["master_id", "service_id"],
                "verbose_name": "Связь мастера с услугой",
                "verbose_name_plural": "Связи мастеров с услугами",
            },
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="answer",
            field=models.TextField(verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="category_slug",
            field=models.SlugField(
                blank=True, default="", max_length=100, verbose_name="Код раздела"
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
                verbose_name="Идентификатор в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="external_updated_at",
            field=models.DateTimeField(
                help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5).",
                verbose_name="Изменено в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="question",
            field=models.CharField(max_length=500, verbose_name="Вопрос"),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="raw",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сырой ответ источника"
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                verbose_name="Синхронизировано",
            ),
        ),
        migrations.AlterField(
            model_name="catalogfaq",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="answer",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
                verbose_name="Идентификатор в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="external_updated_at",
            field=models.DateTimeField(
                help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5).",
                verbose_name="Изменено в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Показывается"),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="question",
            field=models.CharField(max_length=500, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="raw",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сырой ответ источника"
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                verbose_name="Синхронизировано",
            ),
        ),
        migrations.AlterField(
            model_name="cataloghelparticle",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Момент, когда мастер впервые оказалась связанной с BotUser и принявшей приглашение — состояние M1 из docs/design/policies/master-onboarding-m0-m7.md §4.1. Ставит его ``save()`` (см. ниже), поэтому забыть его на новом пути приземления нельзя. Не стирается: это дата события, а не флаг. NULL у синхронизированных мастеров — они в бот не приземлялись.",
                null=True,
                verbose_name="Приглашение принято",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                help_text='Адрес мастера, зеркалится из ключа ``address`` фида специалистов. NULL — ключа в слепке не было (не знаем); "" — ключ был и нёс пустое (источник ответил «нет»). Разница обязательна: подставленное значение неотличимо от настоящего.',
                max_length=500,
                null=True,
                verbose_name="Адрес приёма",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="archive_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Owner-provided rationale for the most recent deactivation (MM5 Step 3, «Причина»). Persisted as a forensic note next to the AuditLog row; cleared on reactivate so the next deactivation starts fresh.",
                verbose_name="Причина архива",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="В архиве с"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="ayla_user_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla user_id (UUID) for this master. Bridge for event-payload master_user_id → CatalogMaster ORM JOIN. Nullable because legacy mysite-synced rows lack this — back-filled by catalog-sync service or master event consumer.",
                null=True,
                verbose_name="Идентификатор пользователя в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="О себе"),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="cache_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Slot-cache staleness counter, incremented on every master.schedule.updated event. Future cache layers (Redis, in-memory) include this in their key so increments transparently invalidate stale slot lookups. No active cache layer reads this today — it's a forward-compatible signal.",
                verbose_name="Версия кеша",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="experience",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Опыт"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
                verbose_name="Идентификатор в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="external_updated_at",
            field=models.DateTimeField(
                help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5).",
                verbose_name="Изменено в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="invite_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="invited_at + 7d (Q-MM2). Past-expiry tokens 410.",
                null=True,
                verbose_name="Приглашение действует до",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="invite_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending invite"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Default PENDING (DRF-1496): a master born by sync was never invited, so she is not bookable until an operator verifies her by hand (journaled admin action). The pre-DRF-1496 default was ACCEPTED; rows that existed on 04.09.2026 were grandfathered as ACCEPTED by migration 0017 so the pilot's booking pick-list did not silently collapse. Invite create-path writes PENDING explicitly, as before.",
                max_length=16,
                verbose_name="Состояние приглашения",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="invite_token",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="One-shot opaque token from MM2 invite-create. Cleared on accept; uniqueness enforced so a stale token can't collide.",
                null=True,
                unique=True,
                verbose_name="Одноразовый ключ приглашения",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="invited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Приглашение выписано"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Активна по данным синхронизации"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="linked_bot_user",
            field=models.OneToOneField(
                blank=True,
                help_text="MAX/Telegram BotUser this master signs in with. SET_NULL on BotUser delete preserves the master audit trail.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="master_identity",
                to="identity.botuser",
                verbose_name="Связанный аккаунт в мессенджере",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="location_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Широта из ключа ``location_lat``. NULL — координаты нет (ключ отсутствовал либо нёс null). НИКОГДА не 0.0: пара нулей — точка в Гвинейском заливе, неотличимая от настоящей.",
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="location_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Долгота из ключа ``location_lng``. NULL — координаты нет (ключ отсутствовал либо нёс null). НИКОГДА не 0.0 — см. ``location_lat``.",
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="max_handle",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Ник в MAX"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="mode",
            field=models.CharField(
                choices=[
                    ("invite", "Invite-based access"),
                    ("catalog_only", "Catalog only (no login)"),
                ],
                default="catalog_only",
                max_length=16,
                verbose_name="Режим работы с ботом",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя мастера"),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="photo_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Ссылка на фото"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Mirrored from the source feed. Domain is 1..5, so a stored 0.00 means «no rating yet», not «rated zero» — it is never rendered (DRF-1224) and takes no part in discovery ordering (DRF-1535).",
                max_digits=3,
                null=True,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="raw",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сырой ответ источника"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="review_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of reviews backing ``rating``, mirrored from Ayla's ``reviews_count``. Written by catalog sync (``catalog/services/upserter._master_fields``) and read by nobody: discovery neither ranks nor filters on it, and there is no trust-score behind it. Collecting reviews is DRF-1527; until that lands this is 0 on every pilot row.",
                verbose_name="Отзывов",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="specialization",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Специализация"
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                verbose_name="Синхронизировано",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="catalogmaster",
            name="yclients_staff_id",
            field=models.IntegerField(
                blank=True,
                help_text="YClients staff id — pre-populated from mysite so the Phase 1 booking flow can dispatch without a second lookup.",
                null=True,
                verbose_name="Идентификатор в YClients",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="ayla_service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla Service.id (UUID). Lookup key for the apps/eventbus service.updated consumer. Coexists with legacy integer external_id while mysite sync still runs; a separate cleanup PR removes external_id once mysite is fully retired.",
                null=True,
                verbose_name="Идентификатор услуги в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="cache_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mirror-staleness counter, incremented on every service.updated event. Downstream cache layers include it in their cache key so increments transparently invalidate stale entries. No active cache reads it today.",
                verbose_name="Версия кеша",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="contraindications",
            field=models.TextField(
                blank=True, default="", verbose_name="Противопоказания"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="duration_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Длительность, мин"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                help_text="Legacy mysite integer PK. Nullable since S3B re-keyed the mirror onto the Ayla stable-id (UUID): Ayla-fed rows leave this NULL and key on (tenant, ayla_service_id / ayla_user_id). Kept for legacy rows — unique_together (tenant, external_id) stays NULL-safe.",
                null=True,
                verbose_name="Идентификатор в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="external_updated_at",
            field=models.DateTimeField(
                help_text="Upstream `updated_at` at last sync. Drives the `?since=` cursor (C2) and last-writer-wins on concurrent beats (C4 Risk #5).",
                verbose_name="Изменено в источнике",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="goals",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Цели клиента (теги)"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Продаётся"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярная"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название услуги"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="price_from",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена от, ₽",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="raw",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Сырой ответ источника"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="requires_health_check",
            field=models.BooleanField(
                default=False, verbose_name="Требует проверки здоровья"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="seo_description",
            field=models.TextField(blank=True, default="", verbose_name="SEO-описание"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="seo_title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="SEO-заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="short_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="Код услуги"),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the platform last touched this row. Differs from `external_updated_at` (upstream's timestamp).",
                verbose_name="Синхронизировано",
            ),
        ),
        migrations.AlterField(
            model_name="catalogservice",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant. CASCADE — mirrors are derived from mysite via catalog sync; tenant delete also drops them.",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="ayla_specialist_service_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Canonical Ayla SpecialistService.id (UUID) — the bookable master↔service edge. NULL means the row was created by an operator (MM4 matrix / invite seeding) and catalog sync must never reconcile it away.",
                null=True,
                verbose_name="Идентификатор связи в Ayla",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Заведена"),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем заведена связь",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="created_by_actor_id",
            field=models.UUIDField(
                blank=True,
                help_text="identity.BotUser.id of the human who caused this edge, when there was one. NULL for machine writers (catalog sync) and for rows predating DRF-975. Not an FK on purpose: this is a forensic stamp that must survive the BotUser row being deleted.",
                null=True,
                verbose_name="Автор (идентификатор в Ayla)",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_offered",
                to="catalog.catalogmaster",
                verbose_name="Мастер",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="resolved_requires_health_check",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Mirrored Ayla SpecialistService.resolved_requires_health_check. NULL = unknown (never synced); the booking health-check gate treats NULL as 'screening required'.",
                null=True,
                verbose_name="Требует проверки здоровья (итог)",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masters_offering",
                to="catalog.catalogservice",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Which writer created this edge (apps.catalog.provenance.MasterServiceSource). NULL = created before DRF-975 shipped; author unrecoverable.",
                max_length=32,
                null=True,
                verbose_name="Откуда взялась связь",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="master_services",
                to="tenancy.tenant",
                verbose_name="Салон",
            ),
        ),
        migrations.AlterField(
            model_name="masterservice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменена"),
        ),
    ]
