"""Подтверждение расписания — три столбца, §83 / DRF-1521 п. 6.

**Здесь нет и не может быть заполнения данных, и это правило 6 решения
владельца, а не экономия:**

> Нельзя просто проставить ``true`` всем существующим мастерам миграцией.
> Пилотных мастеров нужно проверить и подтвердить отдельно.

Массовая простановка выглядит как «включили функцию», а означает
«объявили проверенным непроверенное» — тот же класс, что подстановка
нормы вместо её отсутствия (OPEN_DECISIONS §65) и умолчание часового
пояса (DRF-1606): значение есть, смысла за ним нет.

Поэтому операции здесь только ``AddField``, и все три поля приезжают
пустыми: по умолчанию расписание НЕ подтверждено (правило 1). Что этого
не обойдут следующей миграцией, держит сторож
``apps/catalog/tests/test_schedule_confirmation.py``.
"""

# Generated by Django 5.2.14 on 2026-09-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_catalogfaq_options_and_more"),
        ("identity", "0023_timezone_unset_is_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogmaster",
            name="schedule_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда владелец салона подтвердил рабочие часы этого мастера. NULL — не подтверждены; по умолчанию так у всех.",
                null=True,
                verbose_name="Расписание подтверждено",
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="schedule_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Кто подтвердил. SET_NULL сохраняет след подтверждения, даже если аккаунт удалён: «подтверждено» и «известно кем» — разные утверждения, и первое не должно исчезать со вторым.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="identity.botuser",
                verbose_name="Кем подтверждено",
            ),
        ),
        migrations.AddField(
            model_name="catalogmaster",
            name="schedule_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отпечаток ИМЕННО ТЕХ часов, которые подтвердили. Без него «подтверждено» означает «кто-то когда-то нажал»: нечем отличить подтверждённую версию часов от нынешней. Формат и состав — apps/catalog/services/schedule_confirmation.py.",
                max_length=128,
                verbose_name="Отпечаток подтверждённых часов",
            ),
        ),
    ]
