"""``MasterService.sellable`` + ``unsellable_reason`` (DRF-1964a).

Зеркало продажи ребра каталога (DRF-1962). Обе колонки — с умолчанием
«продаётся»: существующие строки (и операторские, и синка) остаются
продаваемыми, как были до миграции; менять их будет только синк и только
когда каталог пришлёт ключ ``sellable``. Порядок выкладки — бот раньше
каталога: без ключа в ответе зеркало не меняется.

Ограничение ``ck_master_service_sellable_has_reason`` проверяется на
существующих строках мгновенно: у всех ``sellable=True`` и пустая причина.
"""

# Generated by Django 5.2.17 on 2026-09-15 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0022_catalogmaster_catalog_specialist_id"),
        ("tenancy", "0016_alter_staffinvite_options_alter_tenant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="masterservice",
            name="sellable",
            field=models.BooleanField(
                default=True,
                help_text="Mirrored Ayla edge `sellable` (DRF-1962). False = the edge stays in the catalog but is not for sale; sale-path readers skip it.",
                verbose_name="Продаётся",
            ),
        ),
        migrations.AddField(
            model_name="masterservice",
            name="unsellable_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="price_below_minimum | inactive | unknown; empty when the edge is for sale.",
                max_length=32,
                verbose_name="Почему не продаётся",
            ),
        ),
        migrations.AddConstraint(
            model_name="masterservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sellable", True), ("unsellable_reason", "")),
                    models.Q(
                        ("sellable", False),
                        models.Q(("unsellable_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ck_master_service_sellable_has_reason",
            ),
        ),
    ]
