# Generated by Django 5.2.14 on 2026-05-22 07:24

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_catalogmaster_archive_reason"),
        ("tenancy", "0009_tenantstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterNotificationPrefs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "new_booking",
                    models.BooleanField(
                        default=True,
                        help_text="«Новая запись» — bot wrote a customer into the master's diary.",
                    ),
                ),
                (
                    "booking_change",
                    models.BooleanField(
                        default=True,
                        help_text="«Изменение записи» — customer rescheduled or cancelled.",
                    ),
                ),
                (
                    "personal_message",
                    models.BooleanField(
                        default=True,
                        help_text="«Личное сообщение клиента» — customer sent free-form text.",
                    ),
                ),
                (
                    "urgent",
                    models.BooleanField(
                        default=True,
                        help_text="«Срочно (HUMAN_LOCKED)» — safety-critical handoff. Forced ON per spec §805; the CheckConstraint below and service-layer validation both block False writes.",
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, help_text="Master switch for the quiet-hours window below."
                    ),
                ),
                (
                    "quiet_start",
                    models.TimeField(
                        default=datetime.time(21, 0),
                        help_text="«с 21:00» — quiet window START in tenant-local TZ.",
                    ),
                ),
                (
                    "quiet_end",
                    models.TimeField(
                        default=datetime.time(9, 0),
                        help_text="«до 09:00» — quiet window END in tenant-local TZ. ``quiet_start > quiet_end`` is legal: overnight window.",
                    ),
                ),
                (
                    "morning_brief",
                    models.BooleanField(
                        default=True,
                        help_text="«Утренний бриф (08:30)» — daily schedule preview. ON per §823.",
                    ),
                ),
                (
                    "evening_summary",
                    models.BooleanField(
                        default=False,
                        help_text="«Вечерний итог» — end-of-shift recap. OFF per §827.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master",
                    models.OneToOneField(
                        help_text="The master this row belongs to. OneToOne by design — M7 is a single screen of per-master toggles, not per-customer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to="catalog.catalogmaster",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. CASCADE — prefs are derived state.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_notification_prefs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Master notification preferences",
                "verbose_name_plural": "Master notification preferences",
                "indexes": [
                    models.Index(fields=["tenant", "master"], name="notificatio_tenant__d6e55a_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("urgent", True)), name="master_notif_urgent_forced_on"
                    )
                ],
            },
        ),
    ]
