# Generated by Django 5.2.14 on 2026-05-11 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("identity", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "IDLE"),
                            ("consulting", "CONSULTING"),
                            ("escalated", "ESCALATED"),
                        ],
                        default="idle",
                        help_text="Lifecycle state. Minimal per ADR-0007; new states land with their writer code in Sprint 3+.",
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("abandoned", "Abandoned"),
                            ("redirected", "Redirected"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Final outcome — set when the conversation is closed by close_conversation() or the cleanup sweep. Empty = open.",
                        max_length=16,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False after explicit close() OR mark_deleted(). The active-uniqueness constraint depends on this flag.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft-delete timestamp. Conversations are forensic data — never hard-deleted from this table; retention sweeps (Sprint 1 pattern) eventually cascade-prune messages.",
                        null=True,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set by record_message() on every insert. Drives the by-recency admin list and inactivity-cleanup queries.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot_user",
                    models.ForeignKey(
                        help_text="The channel-scoped identity who owns this thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning tenant. PROTECT — dropping a tenant must not silently delete its conversation history; it's a billing / legal incident path.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active", "-last_message_at"],
                        name="conversatio_tenant__17db4c_idx",
                    ),
                    models.Index(
                        fields=["bot_user", "-last_message_at"],
                        name="conversatio_bot_use_329181_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                        fields=("bot_user", "tenant"),
                        name="conversation_one_active_per_bot_user_tenant",
                    )
                ],
            },
        ),
    ]
