# Generated by Django 5.2.14 on 2026-05-11 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Source-of-truth message body from the LLM / handler. Markdown / structured. Rendering for the channel happens downstream and is captured in `rendered_text`.",
                    ),
                ),
                (
                    "rendered_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Channel-rendered text — what the user actually saw. Captured for support / forensic replay.",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Action namespace attached to this assistant message: show_masters / show_slots / confirm_booking / etc. Sprint 3+.",
                        max_length=32,
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(
                        blank=True,
                        help_text="Structured payload backing the UI action (see action_type). Never raw PII.",
                        null=True,
                    ),
                ),
                (
                    "tool_call",
                    models.JSONField(
                        blank=True,
                        help_text="Raw OpenAI tool_call object for forensic audit.",
                        null=True,
                    ),
                ),
                ("tool_call_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "trace_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="From current_trace_id() via record_message(). Links this row to the WebhookJournal / Redis Stream / AuditLog / Event chain for the same pipeline turn.",
                        null=True,
                    ),
                ),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalised from conversation.tenant. B3 service enforces the mirror invariant on every record_message() call.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"], name="conversatio_convers_4b968d_idx"
                    ),
                    models.Index(
                        fields=["tenant", "-created_at"], name="conversatio_tenant__691ec4_idx"
                    ),
                    models.Index(
                        fields=["role", "action_type"], name="conversatio_role_0a4aaf_idx"
                    ),
                ],
            },
        ),
    ]
