# Generated by Django 5.2.14 on 2026-05-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_message"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="bot_user",
            field=models.ForeignKey(
                help_text="The channel-scoped identity who owns this thread. PROTECT (Sprint 2.5 H1): a stray `bot_user.delete()` previously cascaded → Conversation → Message hard-delete, bypassing the soft-delete invariant + leaving no audit trail. Forces callers through `apps.identity.services.delete_bot_user_data()` which soft-deletes conversations first, then deletes the BotUser.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversations",
                to="identity.botuser",
            ),
        ),
    ]
