# Generated by Django 5.2.14 on 2026-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_conversation_state_human_handoff"),
        ("identity", "0002_clientprofile"),
        ("tenancy", "0004_tenant_shadow_mode"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="conversation_one_active_per_bot_user_tenant",
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_shadow",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when this row belongs to a shadow-mode turn. Shadow rows are observability artifacts; outbound is suppressed.",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["tenant", "is_shadow", "-created_at"], name="conversatio_tenant__a4a36a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("is_active", True), ("is_shadow", False)
                ),
                fields=("bot_user", "tenant"),
                name="conversation_one_active_per_bot_user_tenant",
            ),
        ),
    ]
