# Generated by Django 5.2.14 on 2026-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0005_remove_conversation_conversation_one_active_per_bot_user_tenant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="skill_state",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-skill FSM state {skill_name: state_dict}. Sprint 9 D3 — see apps/skills/fsm.py.",
            ),
        ),
    ]
