# Generated by Django 5.2.14 on 2026-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0011_conversation_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_payment_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ULID of the last cross-service payment.* event that touched this conversation. Handler-level idempotency key: if envelope.event_id matches this, the handler short-circuits before side-effects. Mirrors the RemoteBookingProxy.last_synced_event_id pattern from #442. Forensic trace, NOT the primary idempotency guard — that's IngestDedupe at the dispatcher layer.",
                max_length=26,
            ),
        ),
    ]
