# Generated by Django 5.2.14 on 2026-05-27 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_conversation_last_payment_event_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aidraft",
            new_name="conversatio_tenant__776ff2_idx",
            old_name="conv_aidraft_tnt_mst_stat_idx",
        ),
        migrations.RenameIndex(
            model_name="aidraft",
            new_name="conversatio_convers_85b2d8_idx",
            old_name="conv_aidraft_conv_created_idx",
        ),
    ]
