# Generated by Django 5.2.14 on 2026-07-03 03:57
#
# #1066 (completes #1058 end-to-end) — widen
# Conversation.last_payment_event_id from varchar(26) (ULID width) to
# varchar(36) so Ayla's uuid4() (36 chars) fits. #1067 widened the
# eventbus dedupe/DLQ columns; without this one, a real 36-char payment.*
# event passes IngestDedupe but the consumer's write of
# last_payment_event_id still raises Postgres DataError → HANDLER_EXCEPTION
# → 500 → Ayla retries forever. Tech-lead authorized this cross-app touch
# in #1066.
#
# Migration safety: varchar length INCREASE only. Postgres does NOT
# rewrite the table or reindex for a varchar length increase (catalog
# atttypmod bump under a brief sub-ms ACCESS EXCLUSIVE lock; no row scan).
# No data loss; existing 26-char rows untouched. Reverse (36→26) is
# forward-safe: Postgres ABORTS loudly with "value too long" if any
# >26-char row exists — never silent truncation.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0013_rename_conv_aidraft_tnt_mst_stat_idx_conversatio_tenant__776ff2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="last_payment_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cross-service event_id (bare ULID 26 chars or Ayla uuid4 36 chars, #1058) of the last payment.* event that touched this conversation. Handler-level idempotency key: if envelope.event_id matches this, the handler short-circuits before side-effects. Mirrors the RemoteBookingProxy.last_synced_event_id pattern from #442. Forensic trace, NOT the primary idempotency guard — that's IngestDedupe at the dispatcher layer.",
                max_length=36,
            ),
        ),
    ]
