# Generated by Django 5.2.14 on 2026-08-22 06:02
"""DRF-1061 step 0 — the employee's dialogue with the assistant.

Two new tables, deliberately not new columns on ``Conversation``: that
table is the customer thread and eighteen modules read it on that
assumption. Additive only — nothing existing is altered, so the migration
cannot disturb a live conversation.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    # Deliberately the *creating* migrations of the referenced models, not
    # the leaf `makemigrations` picks by default. A leaf pin puts this
    # migration inside the blast radius of every backwards `migrate` in
    # those apps: `apps/identity/tests/test_memory_entry_step*` roll
    # `identity` down to 0014/0015/0017 through `MigrationExecutor`, and
    # `backwards_plan` unapplies *everything that depends on* the target —
    # which, with a leaf pin, meant DROPping both tables below mid-suite.
    # The fixtures then migrate `identity` forward again, but a dependent
    # is not an ancestor, so nothing re-applied us: every later test that
    # touched the delete cascade hit `relation ... does not exist`.
    # `0001_initial` is what actually creates `identity.BotUser` and
    # `tenancy.Tenant`, is never rolled back, and is the same pin
    # `conversations/0001_initial` already uses.
    dependencies = [
        ("conversations", "0014_widen_event_id_to_36"),
        ("identity", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAssistantThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_at_open",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Primary role when the thread opened (owner / admin / receptionist / master). Not a duplicate of the resolver: it is what explains WHY the assistant answered as it did. After access is revoked (DRF-1227) the resolver returns 'customer', and without this the history stops making sense.",
                        max_length=16,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False once closed. The active-uniqueness constraint depends on this flag.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft-delete stamp (152-ФЗ «удалите мои данные»). Excluded from the uniqueness constraint so a replacement thread can open afterwards.",
                        null=True,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Bumped by record_staff_message via atomic UPDATE, never instance .save() — concurrent turns must not trample each other.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bot_user",
                    models.ForeignKey(
                        help_text="The employee. PROTECT mirrors Conversation.bot_user — deletion goes through the 152-ФЗ service, not a cascade.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_assistant_threads",
                        to="identity.botuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Owning salon. PROTECT — dropping a tenant must not silently erase what its staff were told.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_assistant_threads",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff assistant thread",
                "verbose_name_plural": "Staff assistant threads",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAssistantMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="Position within the thread, 0-based. Ordering on ``created_at`` alone is not enough: a tool round trip writes user / tool / assistant within a few milliseconds, and on a clock with coarse resolution those three share a timestamp — the history then comes back shuffled, handing the model an answer before its question. Assigned under a row lock on the thread."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What was said. For role=tool, the serialised result the assistant was handed.",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which tool produced this turn. Empty for plain talk — the field is what makes «why did it answer that» answerable later.",
                        max_length=64,
                    ),
                ),
                (
                    "trace_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Links the turn to its WebhookJournal row.",
                        null=True,
                    ),
                ),
                ("tokens_in", models.IntegerField(default=0)),
                ("tokens_out", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "llm_provider",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("llm_model", models.CharField(blank=True, default="", max_length=64)),
                (
                    "llm_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="USD cost of the call that produced this turn. Present from the start so the assistant's bill is answerable per person on day one, not after a second migration.",
                        max_digits=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalised from thread.tenant; the service enforces the mirror invariant on every write.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_assistant_messages",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.staffassistantthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff assistant message",
                "verbose_name_plural": "Staff assistant messages",
                "ordering": ["created_at", "seq"],
            },
        ),
        migrations.AddIndex(
            model_name="staffassistantthread",
            index=models.Index(
                fields=["tenant", "is_active", "-last_message_at"],
                name="conversatio_tenant__477067_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffassistantthread",
            index=models.Index(
                fields=["bot_user", "-last_message_at"],
                name="conversatio_bot_use_eab589_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffassistantthread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_active", True)),
                fields=("tenant", "bot_user"),
                name="staff_assistant_thread_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="staffassistantmessage",
            index=models.Index(fields=["thread", "seq"], name="conversatio_thread__eb15d1_idx"),
        ),
        migrations.AddIndex(
            model_name="staffassistantmessage",
            index=models.Index(
                fields=["tenant", "-created_at"], name="conversatio_tenant__b7b2da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffassistantmessage",
            constraint=models.UniqueConstraint(
                fields=("thread", "seq"), name="staff_assistant_message_seq_unique"
            ),
        ),
    ]
