# Generated by Django 5.2.14 on 2026-08-25 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0015_staffassistantthread_staffassistantmessage_and_more"),
        ("tenancy", "0012_alter_tenantstaff_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="anonymized_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which erasure request moved the cutoff — forget_all / account_delete. An audit cannot tell the two apart otherwise.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="anonymized_through",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="DRF-1369 / OD_MEMORY.md §4. Messages created at or before this instant are anonymised: body moved to ArchivedMessage, content/rendered_text blanked in place. NULL = nothing on this thread has been anonymised.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ArchivedMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(help_text="Copied from Message.role.", max_length=16),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Redacted Message.content. NEVER read by a prompt path — the sole sanctioned reader is apps.conversations.erasure.read_anonymized_dialogue.",
                    ),
                ),
                (
                    "rendered_body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Redacted Message.rendered_text — what the person actually saw on their screen. Same read rule as `body`.",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "action_data",
                    models.JSONField(
                        blank=True,
                        help_text="Redacted Message.action_data. It is not metadata: the clarification block carries the question the person was asked and the options they were offered, verbatim, and the MAX handler reads it back to rebuild a pending multi-select. Blanking content while leaving this behind left the words on a prompt path — the registry guard caught exactly that.",
                        null=True,
                    ),
                ),
                (
                    "tool_call",
                    models.JSONField(
                        blank=True,
                        help_text="Redacted Message.tool_call — the model's arguments quote the person's phrasing. Archived for the same forensic reason the column exists at all.",
                        null=True,
                    ),
                ),
                (
                    "original_created_at",
                    models.DateTimeField(
                        help_text="Message.created_at. The archive orders by this, not by archived_at — a review reads the dialogue, not the sweep."
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retention_until",
                    models.DateTimeField(
                        db_index=True,
                        help_text="The named term. purge_expired_archived_messages hard-deletes the row past this instant.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("forget_all", "«Забудь всё» (memory erasure)"),
                            ("account_delete", "152-ФЗ delete-my-data"),
                        ],
                        help_text="Which erasure request produced this row.",
                        max_length=32,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="PROTECT: the archive is the incident-review record; a stray conversation delete must not take it with it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_messages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        help_text="The row whose body was moved here. OneToOne makes re-running the anonymiser a no-op at the database level rather than by the caller's good behaviour.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_body",
                        to="conversations.message",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Mirrors the archived Message.tenant so the cross-tenant leakage scanner covers this model like every other.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_messages",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived message",
                "verbose_name_plural": "Archived messages",
                "ordering": ["original_created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "original_created_at"],
                        name="conversatio_convers_4e8077_idx",
                    )
                ],
            },
        ),
    ]
