# Generated by Django 5.2.17 on 2026-09-28 08:03
"""Канал ввода реплики — ``Message.input_channel`` (DRF-2488).

``voice`` — ``content`` получен расшифровкой голосового (DRF-1942),
``text`` — реплика набрана. Существующие строки получают ``text``: до
этой миграции голосовой ввод не помечался, и отличить расшифровку от
набранного текста задним числом нельзя.

### Почему ``db_default``, а не только ``default``

deploy-dev.yml гоняет ``migrate`` через ``run --rm web``, пока старые
web/worker/celery ещё живы и пишут реплики кодом, который про колонку
не знает. С одним ``default`` Django после ADD COLUMN снимает DEFAULT со
столбца — INSERT старого кода упал бы на NOT NULL. ``db_default``
оставляет DEFAULT в схеме; это же страхует откат кода без отката схемы.

### Deploy note

PostgreSQL 16: ``ALTER TABLE … ADD COLUMN … DEFAULT 'text' NOT NULL`` с
константным DEFAULT — операция только над метаданными, таблица
сообщений не переписывается, и следом не идёт ``DROP DEFAULT``. Но
короткий ``ACCESS EXCLUSIVE`` на горячей таблице всё равно берётся и
ждёт текущие запросы — катить вне пика. Откат (``REMOVE COLUMN``) так же
быстрый: колонка без индекса.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0016_conversation_anonymized_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="input_channel",
            field=models.CharField(
                choices=[("text", "Text"), ("voice", "Voice (transcript)")],
                db_default="text",
                default="text",
                help_text="Как человек передал реплику (DRF-1942 / DRF-2488): voice — content получен расшифровкой голосового; text — набран. Голосовое без расшифровки (отказ, флаг выключен, под оператором на салонном пути) — text с пустым content. Аудио не хранится.",
                max_length=16,
            ),
        ),
    ]
